import initSqlJs from 'sql.js'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')

const KEYWORDS = [
  { keyword: "if", language: "python", category: "控制流", definition: "条件判断语句，当条件为 True 时执行缩进的代码块。\nConditional statement that executes the indented block when the condition is True.", code_example: "age = 18\nif age >= 18:\n    print(\"已成年\")", usage_context: ["条件分支", "数据验证", "权限控制"], common_mistakes: ["忘记冒号 :", "缩进不一致", "用 = 代替 ==", "混淆链式比较和 and"] },
  { keyword: "elif", language: "python", category: "控制流", definition: "else if 的缩写，用于多条件分支链中检查额外条件。\nShorthand for else if, used to check additional conditions in a chain.", code_example: "score = 85\nif score >= 90:\n    print(\"A\")\nelif score >= 80:\n    print(\"B\")\nelse:\n    print(\"C\")", usage_context: ["多条件分支", "等级判定", "状态机"], common_mistakes: ["写成 else if", "elif 后没有条件", "顺序错误导致分支不可达"] },
  { keyword: "else", language: "python", category: "控制流", definition: "与 if/elif/for/while/try 搭配，表示\"否则\"或\"正常完成时\"的分支。\nPairs with if/elif/for/while/try for \"otherwise\" or \"completed normally\" branches.", code_example: "for i in range(3):\n    print(i)\nelse:\n    print(\"循环正常结束\")", usage_context: ["条件分支默认情况", "循环正常完成时执行", "try 正常完成"], common_mistakes: ["忘记 else 也可以配合 for/while 使用", "在 else 中 break 不会跳过 else"] },
  { keyword: "for", language: "python", category: "控制流", definition: "遍历可迭代对象（列表、字符串、range 等）的循环语句。\nLoop statement that iterates over iterable objects.", code_example: "fruits = [\"apple\", \"banana\", \"cherry\"]\nfor fruit in fruits:\n    print(fruit)", usage_context: ["遍历列表", "计数循环", "数据处理"], common_mistakes: ["在循环内修改正在遍历的列表", "混淆 for...in 和 for...of", "忘记 range() 左闭右开"] },
  { keyword: "while", language: "python", category: "控制流", definition: "当条件为 True 时重复执行代码块，适合不确定次数的循环。\nRepeatedly executes while condition is True.", code_example: "count = 0\nwhile count < 5:\n    print(count)\n    count += 1", usage_context: ["游戏主循环", "等待条件满足", "读取输入直到特定值"], common_mistakes: ["忘记更新循环变量导致死循环", "条件永远为 True", "用 while True 忘记 break"] },
  { keyword: "break", language: "python", category: "控制流", definition: "立即终止当前循环，跳出最近的 for/while 循环。\nImmediately exits the innermost for/while loop.", code_example: "for i in range(10):\n    if i == 5:\n        break\n    print(i)  # 0 1 2 3 4", usage_context: ["搜索到目标后退出", "提前终止循环", "避免无限循环"], common_mistakes: ["在嵌套循环中只跳出内层循环", "误以为 break 会跳过 else 块"] },
  { keyword: "continue", language: "python", category: "控制流", definition: "跳过当前循环的剩余部分，直接进入下一次迭代。\nSkips the rest of the current iteration and continues to the next.", code_example: "for i in range(5):\n    if i == 2:\n        continue\n    print(i)  # 0 1 3 4", usage_context: ["跳过特定条件", "过滤数据", "减少嵌套层级"], common_mistakes: ["混淆 break 和 continue", "在 continue 之后的代码不会执行但容易忽略"] },
  { keyword: "pass", language: "python", category: "控制流", definition: "空操作语句，什么都不做。用作占位符，让语法上需要语句的地方不报错。\nNull operation; does nothing. Used as a placeholder.", code_example: "class EmptyClass:\n    pass\n\ndef todo():\n    pass  # 待实现", usage_context: ["空类定义", "待实现的函数", "占位的条件分支"], common_mistakes: ["忘记在需要语句的地方加 pass 导致语法错误", "以为 pass 有其他作用"] },
  { keyword: "def", language: "python", category: "函数", definition: "定义一个函数。\nDefines a function.", code_example: "def greet(name):\n    return f\"Hello, {name}!\"", usage_context: ["封装逻辑", "代码复用", "组织程序结构"], common_mistakes: ["忘记冒号 :", "缩进错误", "忘记 return 导致返回 None"] },
  { keyword: "return", language: "python", category: "函数", definition: "从函数中返回一个值并结束函数执行。无 return 的函数返回 None。\nReturns a value from a function and exits it.", code_example: "def add(a, b):\n    return a + b\n\ndef log(msg):\n    print(msg)  # 隐式返回 None", usage_context: ["返回计算结果", "提前退出函数", "返回多个值（元组）"], common_mistakes: ["函数无返回值以为返回 0", "在生成器中混淆 return 和 yield"] },
  { keyword: "lambda", language: "python", category: "函数", definition: "创建匿名的单行函数，常用于需要函数对象的简短场景。\nCreates an anonymous single-expression function.", code_example: "square = lambda x: x ** 2\nprint(square(5))  # 25", usage_context: ["排序的 key 参数", "map/filter 回调", "GUI 事件处理"], common_mistakes: ["在 lambda 中写多行逻辑", "过度使用降低可读性", "忘记 lambda 只能有一个表达式"] },
  { keyword: "yield", language: "python", category: "函数", definition: "将函数变为生成器，每次调用 next() 时从 yield 处恢复执行。\nTurns a function into a generator; resumes from yield on each next().", code_example: "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1", usage_context: ["处理大数据集", "惰性求值", "实现迭代器协议"], common_mistakes: ["混淆 return 和 yield", "忘记生成器是惰性的", "生成器只能遍历一次"] },
  { keyword: "global", language: "python", category: "函数", definition: "在函数内部声明变量为全局作用域，允许修改模块级变量。\nDeclares a variable as global inside a function.", code_example: "count = 0\n\ndef increment():\n    global count\n    count += 1", usage_context: ["修改全局计数器", "配置状态管理", "单例模式"], common_mistakes: ["不加 global 就尝试修改全局变量", "过度使用导致代码难以维护", "与 nonlocal 混淆"] },
  { keyword: "nonlocal", language: "python", category: "函数", definition: "在嵌套函数中声明变量引用外层函数的局部变量。\nDeclares a variable to refer to the enclosing function's scope.", code_example: "def outer():\n    x = 0\n    def inner():\n        nonlocal x\n        x += 1\n    inner()\n    print(x)  # 1", usage_context: ["闭包中修改外部变量", "装饰器实现", "工厂函数"], common_mistakes: ["与 global 混淆", "在外层函数没有定义该变量时报错"] },
  { keyword: "class", language: "python", category: "面向对象", definition: "定义一个类，用于创建对象的蓝图。\nDefines a class, a blueprint for creating objects.", code_example: "class Dog:\n    def __init__(self, name):\n        self.name = name\n\n    def bark(self):\n        return f\"{self.name} says woof!\"", usage_context: ["面向对象编程", "数据建模", "设计模式"], common_mistakes: ["忘记 self 参数", "忘记 __init__ 中初始化属性", "混淆类变量和实例变量"] },
  { keyword: "self", language: "python", category: "面向对象", definition: "实例方法的第一个参数，指向调用该方法的实例对象。\nFirst parameter of instance methods, referring to the calling instance.", code_example: "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increment(self):\n        self.count += 1", usage_context: ["访问实例属性", "调用其他实例方法", "在 __init__ 中初始化"], common_mistakes: ["忘记写 self", "把 self 当作关键字（它只是约定名称）", "在类方法中混淆 self 和 cls"] },
  { keyword: "super", language: "python", category: "面向对象", definition: "调用父类的方法，常用于在子类中扩展父类的 __init__。\nCalls a method from the parent class.", code_example: "class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed", usage_context: ["继承中调用父类方法", "扩展 __init__", "MRO 方法解析"], common_mistakes: ["Python 2 的 super 写法不同", "忘记传参数给 super().__init__", "在多继承中对 super 的误解"] },
  { keyword: "import", language: "python", category: "模块", definition: "导入模块或模块中的特定对象，使我们可以使用其他文件或库中的代码。\nImports a module or specific objects from a module.", code_example: "import math\nprint(math.pi)\n\nfrom os.path import exists", usage_context: ["使用标准库", "导入第三方包", "组织大型项目"], common_mistakes: ["循环导入导致 ImportError", "导入不存在的模块名", "导入名称冲突"] },
  { keyword: "from", language: "python", category: "模块", definition: "与 import 搭配，从模块中导入特定对象。\nUsed with import to import specific objects from a module.", code_example: "from datetime import datetime, timedelta\nfrom os.path import exists, join", usage_context: ["导入特定函数/类", "减少命名前缀", "按需导入"], common_mistakes: ["from x import * 污染命名空间", "导入路径错误"] },
  { keyword: "as", language: "python", category: "模块", definition: "为导入的模块或异常创建别名，或在 with/except 中绑定对象。\nCreates aliases for imports, or binds objects in with/except.", code_example: "import numpy as np\n\ntry:\n    x = 1 / 0\nexcept ZeroDivisionError as e:\n    print(e)", usage_context: ["模块别名", "异常绑定", "with 上下文绑定"], common_mistakes: ["别名与已有名称冲突", "在 except 中忘记用 as 获取错误信息"] },
  { keyword: "try", language: "python", category: "异常处理", definition: "捕获和处理异常，防止程序因未处理的错误而崩溃。\nCatches and handles exceptions to prevent crashes.", code_example: "try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print(\"不能除以零\")\nfinally:\n    print(\"总是执行\")", usage_context: ["文件操作", "网络请求", "用户输入验证", "数据库操作"], common_mistakes: ["except 不指定异常类型", "在 try 中放太多代码", "忘记 finally 会总是执行"] },
  { keyword: "except", language: "python", category: "异常处理", definition: "指定要捕获的异常类型及处理逻辑。\nSpecifies which exception to catch and how to handle it.", code_example: "try:\n    f = open(\"data.txt\")\nexcept FileNotFoundError:\n    print(\"文件不存在\")\nexcept (IOError, OSError) as e:\n    print(f\"IO 错误: {e}\")", usage_context: ["捕获特定异常", "多种异常分别处理", "记录错误日志"], common_mistakes: ["捕获过于宽泛的 Exception", "不处理异常只是 pass", "except 中再次出错"] },
  { keyword: "finally", language: "python", category: "异常处理", definition: "无论 try 块是否发生异常都会执行的清理代码。\nCleanup code that always executes, whether or not an exception occurred.", code_example: "f = None\ntry:\n    f = open(\"data.txt\")\n    content = f.read()\nfinally:\n    if f:\n        f.close()", usage_context: ["资源清理", "关闭文件/连接", "释放锁"], common_mistakes: ["在 finally 中 return 会覆盖异常", "以为 finally 不会在正常情况下执行"] },
  { keyword: "raise", language: "python", category: "异常处理", definition: "主动抛出异常，用于通知调用者出现了错误情况。\nRaises an exception to signal an error condition.", code_example: "def divide(a, b):\n    if b == 0:\n        raise ValueError(\"除数不能为零\")\n    return a / b", usage_context: ["参数校验", "自定义异常", "错误传播"], common_mistakes: ["raise 后面的代码不会执行", "raise 和 return 的交互", "不使用内置异常类型"] },
  { keyword: "None", language: "python", category: "数据类型", definition: "表示\"空\"或\"无\"的特殊对象，是 NoneType 的唯一实例。\nRepresents the absence of a value; the sole instance of NoneType.", code_example: "result = None\nif result is None:\n    print(\"没有结果\")", usage_context: ["函数默认返回值", "表示缺失数据", "可选参数的默认值"], common_mistakes: ["用 == 而不是 is 来比较 None", "以为 None 是 0 或 False", "可变默认参数陷阱"] },
  { keyword: "True", language: "python", category: "数据类型", definition: "布尔类型真值。在 Python 中，True 是整数 1 的子类。\nBoolean true value. In Python, True is a subclass of int.", code_example: "is_valid = True\nif is_valid:\n    print(\"验证通过\")\n\nprint(True + True)  # 2", usage_context: ["条件判断", "标志变量", "布尔运算"], common_mistakes: ["拼写成 true（小写）", "不理解 True 是 int 子类", "不理解短路求值返回的是操作数而非布尔值"] },
  { keyword: "False", language: "python", category: "数据类型", definition: "布尔类型假值。在 Python 中，False 是整数 0 的子类。\nBoolean false value. In Python, False is a subclass of int.", code_example: "is_active = False\nif not is_active:\n    print(\"未激活\")\n\nprint(False + False)  # 0", usage_context: ["条件判断", "标志变量", "布尔运算"], common_mistakes: ["拼写成 false（小写）", "各种假值的混淆（0, '', [], None, False）"] },
  { keyword: "and", language: "python", category: "运算符", definition: "逻辑与运算符。当两个操作数都为 True 时返回 True，否则返回第一个假值。\nLogical AND; returns the first falsy value or the last value.", code_example: "if x > 0 and x < 10:\n    print(\"x 在 0-10 之间\")\n\nresult = 0 and \"hello\"  # 0", usage_context: ["组合多个条件", "短路求值", "防御性编程"], common_mistakes: ["不理解返回的是操作数而非布尔值", "混淆 & (位运算) 和 and"] },
  { keyword: "or", language: "python", category: "运算符", definition: "逻辑或运算符。当任一操作数为 True 时返回第一个真值。\nLogical OR; returns the first truthy value or the last value.", code_example: "name = \"\" or \"Anonymous\"\nprint(name)  # Anonymous", usage_context: ["默认值设置", "条件组合", "短路求值"], common_mistakes: ["混淆 | (位运算) 和 or", "不理解返回的是操作数而非布尔值"] },
  { keyword: "not", language: "python", category: "运算符", definition: "逻辑非运算符，对布尔值取反。\nLogical NOT; inverts a boolean value.", code_example: "is_active = False\nif not is_active:\n    print(\"未激活\")", usage_context: ["条件取反", "检查空容器", "布尔标志翻转"], common_mistakes: ["用 not x == y 代替 x != y", "多重否定降低可读性"] },
  { keyword: "in", language: "python", category: "运算符", definition: "成员运算符，检查元素是否在序列中。\nMembership operator; checks if an element is in a sequence.", code_example: "fruits = [\"apple\", \"banana\"]\nif \"apple\" in fruits:\n    print(\"有苹果\")", usage_context: ["列表包含检查", "字典键存在性", "字符串子串判断"], common_mistakes: ["在大列表上频繁使用 in（应改用 set）", "字典中用 in 检查的是键不是值"] },
  { keyword: "is", language: "python", category: "运算符", definition: "身份运算符，检查两个变量是否引用同一个对象。\nIdentity operator; checks if two variables reference the same object.", code_example: "a = [1, 2, 3]\nb = [1, 2, 3]\nprint(a == b)  # True\nprint(a is b)  # False", usage_context: ["与 None 比较", "单例模式检查", "区分 == 和 is"], common_mistakes: ["用 == 比较 None", "不理解 is 比较的是 id 而不是值", "小整数缓存导致的混淆"] },
  { keyword: "with", language: "python", category: "上下文管理", definition: "上下文管理器，自动管理资源的获取和释放。\nContext manager that automatically manages resource acquisition and release.", code_example: "with open(\"data.txt\", \"r\") as f:\n    content = f.read()\n# 文件在此自动关闭", usage_context: ["文件操作", "数据库连接", "线程锁", "临时修改状态"], common_mistakes: ["不用 with 打开文件导致资源泄漏", "不理解 __enter__ 和 __exit__", "与 try/finally 功能重叠"] },
  { keyword: "@decorator", language: "python", category: "装饰器/元编程", definition: "用 @ 语法将一个函数包装到另一个函数中，常用于日志、权限、缓存等横切关注点。\nWraps a function with another using @syntax for cross-cutting concerns.", code_example: "def log_calls(func):\n    def wrapper(*args, **kwargs):\n        print(f\"Calling {func.__name__}\")\n        return func(*args, **kwargs)\n    return wrapper\n\n@log_calls\ndef add(a, b):\n    return a + b", usage_context: ["日志记录", "权限验证", "缓存", "重试逻辑"], common_mistakes: ["不使用 functools.wraps 丢失元信息", "装饰器执行顺序（从下往上）", "忘记返回 wrapper"] },
  { keyword: "@property", language: "python", category: "装饰器/元编程", definition: "将方法变为只读属性，允许以属性访问语法调用方法。\nTurns a method into a read-only property.", code_example: "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    @property\n    def area(self):\n        return 3.14 * self.radius ** 2\n\nc = Circle(5)\nprint(c.area)  # 78.5", usage_context: ["计算属性", "数据验证", "向后兼容 API"], common_mistakes: ["忘记加 @setter", "在 property 中访问 self 导致无限递归"] },
  { keyword: "list comprehension", language: "python", category: "推导式", definition: "用简洁语法创建列表的表达式。比 for 循环更 Pythonic。\nConcise syntax for creating lists. More Pythonic than for loops.", code_example: "squares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]", usage_context: ["数据转换", "过滤列表", "扁平化嵌套"], common_mistakes: ["过于复杂的推导式降低可读性", "变量泄漏到外部作用域", "混淆列表推导和生成器表达式"] },
  { keyword: "async", language: "python", category: "异步", definition: "声明异步函数或异步上下文管理器，配合 await 使用。\nDeclares an asynchronous function or context manager.", code_example: "import asyncio\n\nasync def fetch_data():\n    await asyncio.sleep(1)\n    return \"data\"", usage_context: ["网络请求", "IO 密集型任务", "并发编程"], common_mistakes: ["不理解事件循环", "不必要的串行 await", "在同步代码中调用异步函数"] },
  { keyword: "await", language: "python", category: "异步", definition: "暂停当前协程的执行，等待异步操作完成。\nPauses the current coroutine until the awaitable completes.", code_example: "async def main():\n    result = await fetch_data()\n    print(result)", usage_context: ["等待异步结果", "IO 操作", "并发任务"], common_mistakes: ["在非 async 函数中使用 await", "忘记 await 协程不会自动执行"] },
  { keyword: "assert", language: "python", category: "调试", definition: "断言语句，如果条件为 False 则抛出 AssertionError。\nAssertion statement; raises AssertionError if condition is False.", code_example: "def divide(a, b):\n    assert b != 0, \"除数不能为零\"\n    return a / b", usage_context: ["单元测试", "参数验证", "调试"], common_mistakes: ["在生产代码中依赖 assert（可被 -O 禁用）", "在 assert 中写有副作用的表达式"] },
  { keyword: "del", language: "python", category: "数据类型", definition: "删除变量引用或集合中的元素。\nDeletes a variable binding or an item from a collection.", code_example: "x = 10\ndel x  # x 不再存在\n\nlst = [1, 2, 3]\ndel lst[1]  # [1, 3]", usage_context: ["删除变量", "删除列表元素", "删除字典键"], common_mistakes: ["删除不存在的键会 KeyError", "del 删除的是引用不是对象本身"] },
  { keyword: "dict", language: "python", category: "数据类型", definition: "键值对数据结构，Python 3.7+ 保持插入有序。\nKey-value data structure; insertion-ordered since Python 3.7.", code_example: "person = {\"name\": \"Alice\", \"age\": 30}\nfor key, value in person.items():\n    print(f\"{key}: {value}\")", usage_context: ["配置管理", "JSON 数据", "计数器", "缓存"], common_mistakes: ["可变对象不能作为键", "遍历时修改字典", "KeyError 访问不存在的键"] },
  { keyword: "set", language: "python", category: "数据类型", definition: "无序不重复元素集合，支持数学集合运算。\nUnordered collection of unique elements with set operations.", code_example: "a = {1, 2, 3}\nb = {3, 4, 5}\nprint(a | b)  # {1, 2, 3, 4, 5}\nprint(a & b)  # {3}", usage_context: ["去重", "成员测试", "集合运算（交并差）"], common_mistakes: ["Set 没有下标访问", "以为 set 是有序的", "可变对象不能放入 set"] },
  { keyword: "let", language: "javascript", category: "变量声明", definition: "声明一个块级作用域的可变变量。\nDeclares a block-scoped mutable variable.", code_example: "let count = 0;\ncount = 1; // OK\n\nif (true) {\n  let x = 10;\n}\n// console.log(x); // ReferenceError", usage_context: ["需要重新赋值的变量", "循环计数器", "条件分支中的临时变量"], common_mistakes: ["在声明前访问（暂时性死区）", "在同一作用域重复声明", "混淆 let 和 const 的使用场景"] },
  { keyword: "const", language: "javascript", category: "变量声明", definition: "声明一个块级作用域的常量，绑定不可重新赋值（但对象属性可修改）。\nDeclares a block-scoped constant binding (but object properties can be modified).", code_example: "const PI = 3.14159;\nconst arr = [1, 2, 3];\narr.push(4); // OK\n// PI = 3; // Error!", usage_context: ["常量定义", "函数引用", "配置对象", "默认优先使用 const"], common_mistakes: ["以为 const 完全不可变（对象内部可变）", "不初始化就声明", "用 const 声明后又想重新赋值"] },
  { keyword: "var", language: "javascript", category: "变量声明", definition: "声明一个函数作用域的变量（旧语法，建议用 let/const 代替）。\nDeclares a function-scoped variable (legacy; prefer let/const).", code_example: "var x = 10;\nif (true) {\n  var x = 20; // 同一个 x!\n}\nconsole.log(x); // 20", usage_context: ["遗留代码", "需要函数作用域（极少）", "全局变量（不推荐）"], common_mistakes: ["变量提升导致意外行为", "没有块级作用域", "重复声明不报错"] },
  { keyword: "if", language: "javascript", category: "控制流", definition: "条件判断语句，当条件为真时执行代码块。\nConditional statement that executes a block when condition is truthy.", code_example: "const age = 18;\nif (age >= 18) {\n  console.log(\"已成年\");\n} else {\n  console.log(\"未成年\");\n}", usage_context: ["条件分支", "数据验证", "权限控制"], common_mistakes: ["用 = 代替 ==", "忘记花括号", "truthy/falsy 值的陷阱"] },
  { keyword: "else", language: "javascript", category: "控制流", definition: "与 if 搭配，表示条件为假时的分支。\nPairs with if for the falsy branch.", code_example: "const score = 85;\nif (score >= 90) {\n  console.log(\"A\");\n} else {\n  console.log(\"B\");\n}", usage_context: ["默认分支", "三元运算符的替代"], common_mistakes: ["else 悬挂问题（else 匹配最近的 if）"] },
  { keyword: "switch", language: "javascript", category: "控制流", definition: "多分支选择语句，基于值匹配执行不同分支。\nMulti-branch selection based on value matching.", code_example: "const day = \"Monday\";\nswitch (day) {\n  case \"Monday\":\n    console.log(\"周一\");\n    break;\n  case \"Friday\":\n    console.log(\"周五\");\n    break;\n  default:\n    console.log(\"其他\");\n}", usage_context: ["多值匹配", "状态机", "替代多个 if-else"], common_mistakes: ["忘记 break 导致穿透", "switch 使用严格比较（===）", "default 位置不当"] },
  { keyword: "for", language: "javascript", category: "控制流", definition: "循环语句，支持经典 for 循环和 for...of/for...in 变体。\nLoop statement with classic, for...of, and for...in variants.", code_example: "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}\n\nconst arr = [10, 20, 30];\nfor (const item of arr) {\n  console.log(item);\n}", usage_context: ["遍历数组", "计数循环", "遍历对象属性"], common_mistakes: ["用 for...in 遍历数组（应用 for...of）", "闭包中使用 var 导致共享变量"] },
  { keyword: "while", language: "javascript", category: "控制流", definition: "当条件为真时重复执行代码块。\nRepeatedly executes while condition is truthy.", code_example: "let count = 0;\nwhile (count < 5) {\n  console.log(count);\n  count++;\n}", usage_context: ["不确定次数的循环", "等待条件满足", "游戏循环"], common_mistakes: ["忘记更新循环变量导致死循环", "条件永远为真"] },
  { keyword: "break", language: "javascript", category: "控制流", definition: "终止当前循环或 switch 语句。\nExits the current loop or switch statement.", code_example: "for (let i = 0; i < 10; i++) {\n  if (i === 5) break;\n  console.log(i); // 0 1 2 3 4\n}", usage_context: ["搜索到结果后退出", "switch 中防止穿透", "提前终止循环"], common_mistakes: ["在 switch 中忘记 break", "只跳出内层循环"] },
  { keyword: "continue", language: "javascript", category: "控制流", definition: "跳过当前迭代，进入下一次循环。\nSkips the current iteration and continues to the next.", code_example: "for (let i = 0; i < 5; i++) {\n  if (i === 2) continue;\n  console.log(i); // 0 1 3 4\n}", usage_context: ["跳过特定条件", "过滤数据"], common_mistakes: ["混淆 break 和 continue"] },
  { keyword: "function", language: "javascript", category: "函数", definition: "声明一个函数（有提升特性）。\nDeclares a function (hoisted).", code_example: "function greet(name) {\n  return \"Hello, \" + name;\n}\n\nconsole.log(greet(\"World\"));", usage_context: ["通用函数定义", "需要提升的场景", "构造函数（旧式）"], common_mistakes: ["函数声明提升但函数表达式不提升", "回调中 this 丢失"] },
  { keyword: "arrow", language: "javascript", category: "函数", definition: "箭头函数 =>，更简洁的函数语法，不绑定自己的 this。\nArrow function; concise syntax, does not bind its own this.", code_example: "const add = (a, b) => a + b;\nconst square = x => x * x;\n\n[1, 2, 3].map(x => x * 2);", usage_context: ["回调函数", "数组方法链", "不需要自己 this 的场景"], common_mistakes: ["不能用作构造函数", "没有 arguments 对象", "隐式返回对象需要括号"] },
  { keyword: "return", language: "javascript", category: "函数", definition: "从函数返回值并结束执行。\nReturns a value from a function and exits.", code_example: "function add(a, b) {\n  return a + b;\n}\n\n// 箭头函数隐式返回\nconst multiply = (a, b) => a * b;", usage_context: ["返回计算结果", "提前退出函数", "返回 Promise"], common_mistakes: ["函数无返回值返回 undefined", "return 后面的代码不会执行"] },
  { keyword: "async", language: "javascript", category: "异步", definition: "声明异步函数，返回 Promise。\nDeclares an async function that returns a Promise.", code_example: "async function fetchUser(id) {\n  const res = await fetch(\"/api/users/\" + id);\n  return res.json();\n}", usage_context: ["网络请求", "文件操作", "任何返回 Promise 的场景"], common_mistakes: ["忘记 await 导致得到 Promise 而非值", "不必要的串行 await"] },
  { keyword: "await", language: "javascript", category: "异步", definition: "暂停 async 函数执行，等待 Promise 解决。\nPauses async function execution until Promise resolves.", code_example: "async function main() {\n  const data = await fetchData();\n  console.log(data);\n}", usage_context: ["等待异步结果", "顺序执行异步操作"], common_mistakes: ["在非 async 函数中使用", "忘记 await 得到 Promise 对象"] },
  { keyword: "Promise", language: "javascript", category: "异步", definition: "异步操作的容器，代表一个最终会完成或失败的操作。\nContainer for an async operation that will eventually resolve or reject.", code_example: "const p = new Promise((resolve, reject) => {\n  setTimeout(() => resolve(\"done\"), 1000);\n});\n\np.then(console.log).catch(console.error);", usage_context: ["封装异步操作", "并行执行 Promise.all", "链式调用"], common_mistakes: ["Promise 嵌套（应展平）", "忘记 .catch 处理错误", "混淆 Promise 和 Observable"] },
  { keyword: "class", language: "javascript", category: "面向对象", definition: "基于原型的类声明语法（ES6+）。\nPrototype-based class declaration syntax (ES6+).", code_example: "class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n  bark() {\n    return this.name + \" says woof!\";\n  }\n}", usage_context: ["面向对象编程", "React 组件（旧式）", "数据模型"], common_mistakes: ["忘记 new 调用", "类方法不会自动绑定 this", "class 不是真正的类（语法糖）"] },
  { keyword: "this", language: "javascript", category: "面向对象", definition: "指向当前执行上下文的对象（取决于调用方式）。\nRefers to the current execution context object (depends on how called).", code_example: "const obj = {\n  name: \"Alice\",\n  greet() {\n    console.log(this.name);\n  },\n};\nobj.greet(); // \"Alice\"", usage_context: ["访问对象属性", "方法调用", "构造函数中"], common_mistakes: ["回调中 this 丢失", "严格模式下 this 默认为 undefined", "箭头函数不绑定 this"] },
  { keyword: "new", language: "javascript", category: "面向对象", definition: "创建构造函数的实例对象。\nCreates an instance of a constructor function.", code_example: "class Person {\n  constructor(name) {\n    this.name = name;\n  }\n}\nconst p = new Person(\"Alice\");", usage_context: ["创建对象实例", "使用构造函数", "Date/RegExp 等内置类型"], common_mistakes: ["忘记使用 new", "构造函数返回对象时 new 的行为", "不能与箭头函数一起使用"] },
  { keyword: "extends", language: "javascript", category: "面向对象", definition: "创建一个类继承另一个类。\nCreates a class that inherits from another class.", code_example: "class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n}\n\nclass Dog extends Animal {\n  bark() {\n    return this.name + \" barks!\";\n  }\n}", usage_context: ["类继承", "扩展内置类型", "React 组件继承"], common_mistakes: ["忘记调用 super()", "不能继承普通对象", "方法覆盖的注意事项"] },
  { keyword: "import", language: "javascript", category: "模块", definition: "ES 模块语法，导入其他模块导出的绑定。\nES module syntax; imports bindings exported by other modules.", code_example: "import React from \"react\";\nimport { useState, useEffect } from \"react\";\nimport * as utils from \"./utils\";", usage_context: ["导入库", "导入本地模块", "按需导入"], common_mistakes: ["CommonJS 和 ESM 混用", "导入路径错误", "导出的是引用而非值的拷贝"] },
  { keyword: "export", language: "javascript", category: "模块", definition: "从模块中导出函数、对象或原始值。\nExports functions, objects, or primitives from a module.", code_example: "export const PI = 3.14;\nexport function add(a, b) { return a + b; }\nexport default class App {}", usage_context: ["模块化代码", "共享功能", "默认导出 vs 命名导出"], common_mistakes: ["export default 和命名导出混用", "导出的是引用而非值的拷贝"] },
  { keyword: "try", language: "javascript", category: "异常处理", definition: "捕获和处理异常。\nCatches and handles exceptions.", code_example: "try {\n  JSON.parse(\"invalid\");\n} catch (e) {\n  console.error(\"解析错误:\", e.message);\n} finally {\n  console.log(\"总是执行\");\n}", usage_context: ["JSON 解析", "网络请求", "可能出错的操作"], common_mistakes: ["catch 中不处理错误", "finally 中 return 会覆盖异常"] },
  { keyword: "throw", language: "javascript", category: "异常处理", definition: "抛出自定义异常。\nThrows a custom exception.", code_example: "function divide(a, b) {\n  if (b === 0) throw new Error(\"除数不能为零\");\n  return a / b;\n}", usage_context: ["参数校验", "自定义错误", "错误传播"], common_mistakes: ["throw 后面的代码不执行", "throw 非 Error 对象"] },
  { keyword: "typeof", language: "javascript", category: "数据类型", definition: "返回一个值的类型字符串。\nReturns a string indicating the type of a value.", code_example: "typeof 42;        // \"number\"\ntypeof \"hello\";   // \"string\"\ntypeof undefined; // \"undefined\"\ntypeof null;      // \"object\" (bug!)", usage_context: ["类型检查", "参数验证", "防御性编程"], common_mistakes: ["typeof null === 'object'（历史 bug）", "不能区分数组和对象", "typeof [] === 'object'"] },
  { keyword: "instanceof", language: "javascript", category: "数据类型", definition: "检查对象是否是某个构造函数的实例。\nChecks if an object is an instance of a constructor.", code_example: "class Dog {}\nconst d = new Dog();\nconsole.log(d instanceof Dog); // true\n\n[1,2] instanceof Array; // true", usage_context: ["类型检查", "自定义类实例判断", "错误类型判断"], common_mistakes: ["跨 iframe 失效", "不能用于原始类型", "原型链修改影响结果"] },
  { keyword: "null", language: "javascript", category: "数据类型", definition: "表示\"无值\"的特殊关键字，是对象类型的故意空值。\nRepresents an intentional absence of any object value.", code_example: "let user = null;\nif (user === null) {\n  console.log(\"没有用户\");\n}", usage_context: ["初始化变量", "表示空对象", "函数参数默认值"], common_mistakes: ["typeof null === 'object'", "混淆 null 和 undefined", "用 == 而不是 === 比较"] },
  { keyword: "undefined", language: "javascript", category: "数据类型", definition: "变量已声明但未赋值时的默认值。\nDefault value of declared but unassigned variables.", code_example: "let x;\nconsole.log(x); // undefined\n\nfunction foo() {}\nconsole.log(foo()); // undefined", usage_context: ["检查变量是否赋值", "函数无返回值", "缺失的对象属性"], common_mistakes: ["显式赋值 undefined（应用 null）", "混淆 undefined 和 null", "访问不存在的属性返回 undefined"] },
  { keyword: "NaN", language: "javascript", category: "数据类型", definition: "表示\"不是数字\"的特殊值，是 Number 类型的特殊状态。\nRepresents Not-a-Number; a special numeric value.", code_example: "console.log(NaN === NaN); // false!\nconsole.log(isNaN(\"hello\")); // true\nconsole.log(Number.isNaN(NaN)); // true", usage_context: ["数学运算失败", "无效的数字转换"], common_mistakes: ["NaN === NaN 为 false", "用 isNaN 而不是 Number.isNaN", "typeof NaN === 'number'"] },
  { keyword: "===", language: "javascript", category: "运算符", definition: "严格相等运算符，不进行类型转换。\nStrict equality operator; no type coercion.", code_example: "1 === 1;      // true\n\"1\" === 1;    // false\nnull === undefined; // false", usage_context: ["精确比较", "条件判断", "避免类型转换陷阱"], common_mistakes: ["用 == 代替 === 导致隐式转换", "NaN === NaN 为 false", "Object.is 和 === 的细微差别"] },
  { keyword: "??", language: "javascript", category: "运算符", definition: "空值合并运算符，当左侧为 null 或 undefined 时返回右侧值。\nNullish coalescing; returns right side when left is null/undefined.", code_example: "const name = user.name ?? \"匿名\";\nconst port = config.port ?? 3000;\n\n// 区别于 ||\n0 ?? 42;  // 0\n0 || 42; // 42", usage_context: ["默认值设置", "配置合并", "替代 || 的更安全选择"], common_mistakes: ["不能与 || 或 && 混用（需要括号）", "混淆 ?? 和 || 对 0/'' 的处理"] },
  { keyword: "?.", language: "javascript", category: "运算符", definition: "可选链运算符，安全地访问嵌套属性，遇到 null/undefined 短路返回 undefined。\nOptional chaining; safely accesses nested properties.", code_example: "const city = user?.address?.city;\nconst len = arr?.length;\nconst result = obj?.method?.();", usage_context: ["安全访问嵌套属性", "API 响应处理", "DOM 元素访问"], common_mistakes: ["不能用于赋值左侧", "过度使用掩盖了设计问题"] },
  { keyword: "spread", language: "javascript", category: "对象/数组", definition: "展开运算符，将可迭代对象展开为独立元素。\nSpread operator; expands iterables into individual elements.", code_example: "const arr = [1, 2, 3];\nconst copy = [...arr, 4, 5];\n\nconst obj = { a: 1 };\nconst merged = { ...obj, b: 2 };", usage_context: ["复制数组/对象", "合并数组/对象", "函数参数展开"], common_mistakes: ["浅拷贝而非深拷贝", "与剩余参数语法相同但语义不同"] },
  { keyword: "rest", language: "javascript", category: "对象/数组", definition: "剩余参数，将不定数量的参数收集到数组中。\nRest parameters; collects remaining arguments into an array.", code_example: "function sum(...numbers) {\n  return numbers.reduce((a, b) => a + b, 0);\n}\n\nconst [first, ...rest] = [1, 2, 3, 4];", usage_context: ["可变参数函数", "解构中收集剩余", "替代 arguments 对象"], common_mistakes: ["与展开运算符语法相同但语义不同", "只能放在参数列表最后"] },
  { keyword: "destructuring", language: "javascript", category: "对象/数组", definition: "解构赋值，从数组或对象中提取值到变量。\nDestructuring assignment; extracts values from arrays/objects.", code_example: "const [a, b] = [1, 2];\nconst { name, age } = { name: \"Alice\", age: 30 };\n\nfunction greet({ name }) {\n  console.log(\"Hello \" + name);\n}", usage_context: ["函数参数解构", "交换变量", "导入模块部分导出"], common_mistakes: ["不能用于对象解构的中间位置", "解构 undefined/null 会报错", "别名语法 { name: n }"] },
  { keyword: "Symbol", language: "javascript", category: "数据类型", definition: "唯一且不可变的原始值，常用作对象的唯一属性键。\nUnique and immutable primitive; used as unique object property keys.", code_example: "const id = Symbol(\"id\");\nconst obj = { [id]: 123 };\nconsole.log(obj[id]); // 123\n\nSymbol.for(\"key\") === Symbol.for(\"key\"); // true", usage_context: ["唯一属性键", "避免属性名冲突", "内置 Symbol（iterator 等）"], common_mistakes: ["Symbol 不能用 new", "Symbol 不会被 for...in 遍历", "Symbol.for 创建全局共享 Symbol"] },
  { keyword: "Map", language: "javascript", category: "数据类型", definition: "键值对集合，键可以是任何类型，保持插入顺序。\nKey-value collection; keys can be any type, insertion-ordered.", code_example: "const map = new Map();\nmap.set(\"name\", \"Alice\");\nmap.set(1, \"one\");\n\nconsole.log(map.get(\"name\")); // \"Alice\"\nconsole.log(map.size); // 2", usage_context: ["非字符串键", "频繁增删键值对", "需要保持插入顺序"], common_mistakes: ["不能用 {} 字面量创建 Map", "键比较用 SameValueZero", "与普通对象混用"] },
  { keyword: "Set", language: "javascript", category: "数据类型", definition: "唯一值的集合，保持插入顺序。\nCollection of unique values, insertion-ordered.", code_example: "const set = new Set([1, 2, 3, 2, 1]);\nconsole.log(set); // Set {1, 2, 3}\nconsole.log(set.size); // 3\n\n// 数组去重\nconst unique = [...new Set([1, 1, 2, 3, 3])];", usage_context: ["数组去重", "成员测试", "集合运算"], common_mistakes: ["Set 没有下标访问", "对象引用比较（非值比较）"] },
  { keyword: "useState", language: "react", category: "React", definition: "React Hook，为函数组件添加状态。返回 [值, 更新函数]。\nReact Hook that adds state to function components. Returns [value, setter].", code_example: "import { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n}", usage_context: ["表单输入", "开关状态", "计数器", "任何需要随时间变化的数据"], common_mistakes: ["在条件或循环中调用 Hook", "直接修改 state 而非调用 setter", "忘记 state 更新是异步的"] },
  { keyword: "useEffect", language: "react", category: "React", definition: "React Hook，在渲染后执行副作用（数据请求、订阅、DOM 操作）。\nReact Hook for side effects after render (data fetching, subscriptions, DOM manipulation).", code_example: "import { useEffect, useState } from 'react';\n\nfunction UserList() {\n  const [users, setUsers] = useState([]);\n  useEffect(() => {\n    fetch('/api/users').then(r => r.json()).then(setUsers);\n  }, []);\n  return <ul>{users.map(u => <li key={u.id}>{u.name}</li>)}</ul>;\n}", usage_context: ["API 数据获取", "事件监听", "定时器", "同步外部状态"], common_mistakes: ["忘记依赖数组导致无限循环", "依赖数组遗漏导致闭包陷阱", "在 effect 中忘记清理（return 函数）"] },
  { keyword: "useContext", language: "react", category: "React", definition: "React Hook，读取 Context 中的共享值，避免逐层传递 props。\nReact Hook that reads shared values from Context, avoiding prop drilling.", code_example: "const ThemeContext = createContext('light');\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nfunction Toolbar() {\n  const theme = useContext(ThemeContext);\n  return <div className={theme}>Toolbar</div>;\n}", usage_context: ["全局主题", "用户认证状态", "语言切换", "多层组件共享数据"], common_mistakes: ["Context 值变化时所有消费者都会重渲染", "滥用 Context 管理所有状态", "忘记 Provider 包裹"] },
  { keyword: "useRef", language: "react", category: "React", definition: "React Hook，创建一个在渲染间保持的可变引用，修改不触发重渲染。\nReact Hook that creates a mutable ref persisted across renders without triggering re-render.", code_example: "import { useRef } from 'react';\n\nfunction TextInput() {\n  const inputRef = useRef(null);\n  return (\n    <>\n      <input ref={inputRef} />\n      <button onClick={() => inputRef.current.focus()}>聚焦</button>\n    </>\n  );\n}", usage_context: ["DOM 元素引用", "保存定时器 ID", "保存上一次的值", "可变值不触发重渲染"], common_mistakes: ["修改 ref.current 不触发重渲染以为没生效", "在渲染期间读写 ref.current", "混淆 ref 和 state 的使用场景"] },
  { keyword: "props", language: "react", category: "React", definition: "组件的输入参数，父组件通过 JSX 属性传递，子组件只读。\nComponent input parameters passed via JSX attributes; read-only in the child.", code_example: "function Greeting({ name, age }) {\n  return <p>Hello {name}, age {age}</p>;\n}\n\n<Greeting name=\"Alice\" age={30} />", usage_context: ["父传子数据", "回调函数传递", "组件配置", "渲染内容（children）"], common_mistakes: ["直接修改 props", "传递过多 props（应用对象或拆分组件）", "忘记传必需的 props"] },
  { keyword: "JSX", language: "react", category: "React", definition: "JavaScript 的语法扩展，在 JS 中编写类似 HTML 的 UI 结构。\nSyntax extension for writing UI structures in JavaScript.", code_example: "function App() {\n  const name = 'World';\n  return (\n    <div className=\"app\">\n      <h1>Hello, {name}!</h1>\n      {isLoggedIn ? <Dashboard /> : <Login />}\n    </div>\n  );\n}", usage_context: ["组件渲染", "条件渲染", "列表渲染", "组合 UI"], common_mistakes: ["class 要写成 className", "JSX 中不能用 if/for，用三元和 map", "必须有单个根元素（或 Fragment）"] },
  { keyword: "ref", language: "vue", category: "Vue", definition: "Vue 3 Composition API，创建响应式基本类型引用，通过 .value 访问。\nVue 3 Composition API; creates a reactive reference for primitives, accessed via .value.", code_example: "import { ref } from 'vue';\n\nconst count = ref(0);\nconsole.log(count.value); // 0\n\ncount.value++;\n// 模板中自动解包，不需要 .value", usage_context: ["响应式基本类型（string/number/boolean）", "模板中绑定数据", "组件状态"], common_mistakes: ["在 JS 中忘记用 .value 访问", "在模板中多写 .value（自动解包）", "解构后丢失响应性"] },
  { keyword: "reactive", language: "vue", category: "Vue", definition: "Vue 3 Composition API，创建响应式对象，直接访问属性无需 .value。\nVue 3 Composition API; creates a reactive object, accessed directly without .value.", code_example: "import { reactive } from 'vue';\n\nconst state = reactive({\n  name: 'Alice',\n  count: 0,\n});\n\nstate.count++; // 直接修改，自动触发更新", usage_context: ["响应式对象/数组", "复杂表单状态", "多属性聚合状态"], common_mistakes: ["不能用于基本类型（用 ref）", "解构会丢失响应性", "不能替换整个对象（会断开响应）"] },
  { keyword: "computed", language: "vue", category: "Vue", definition: "Vue 3 Composition API，创建基于响应式依赖的计算属性，自动缓存。\nVue 3 Composition API; creates a cached derived value from reactive dependencies.", code_example: "import { ref, computed } from 'vue';\n\nconst firstName = ref('Alice');\nconst lastName = ref('Smith');\nconst fullName = computed(() => firstName.value + ' ' + lastName.value);\n\nconsole.log(fullName.value); // 'Alice Smith'", usage_context: ["派生数据", "过滤/排序列表", "格式化显示", "表单验证"], common_mistakes: ["computed 中有副作用", "忘记 .value 访问", "依赖不变时以为会重新计算（缓存机制）"] },
  { keyword: "watch", language: "vue", category: "Vue", definition: "Vue 3 Composition API，监听响应式数据变化并执行副作用。\nVue 3 Composition API; watches reactive data changes and runs side effects.", code_example: "import { ref, watch } from 'vue';\n\nconst keyword = ref('');\n\nwatch(keyword, (newVal, oldVal) => {\n  console.log(`搜索: ${oldVal} -> ${newVal}`);\n  fetchResults(newVal);\n});", usage_context: ["搜索防抖", "数据持久化", "API 联动", "DOM 操作"], common_mistakes: ["忘记返回值的监听（用 getter 函数）", "watch 对象时需要 deep: true", "忘记清理副作用（onCleanup）"] },
  { keyword: "v-if", language: "vue", category: "Vue", definition: "Vue 指令，根据条件决定是否渲染 DOM 元素（真正移除/创建）。\nVue directive; conditionally renders DOM elements (truly mounts/unmounts).", code_example: "<template>\n  <div v-if=\"isLoggedIn\">\n    <p>欢迎回来，{{ username }}</p>\n  </div>\n  <div v-else>\n    <p>请登录</p>\n  </div>\n</template>", usage_context: ["条件渲染", "权限控制", "加载状态切换"], common_mistakes: ["与 v-show 混淆（v-if 有更高切换开销）", "v-if 和 v-for 不要用在同一元素上", "v-else 必须紧跟 v-if"] },
  { keyword: "v-for", language: "vue", category: "Vue", definition: "Vue 指令，基于数组/对象渲染列表。\nVue directive; renders a list from an array or object.", code_example: "<template>\n  <ul>\n    <li v-for=\"(item, index) in items\" :key=\"item.id\">\n      {{ index }}. {{ item.name }}\n    </li>\n  </ul>\n</template>", usage_context: ["渲染列表", "遍历对象属性", "生成表格行"], common_mistakes: ["忘记 :key（用唯一 id 而非 index）", "v-for 和 v-if 同时使用", "直接修改数组长度不会触发更新"] },
  { keyword: "v-model", language: "vue", category: "Vue", definition: "Vue 指令，实现表单元素与数据的双向绑定。\nVue directive; creates two-way binding between form elements and data.", code_example: "<template>\n  <input v-model=\"username\" />\n  <select v-model=\"city\">\n    <option>北京</option>\n    <option>上海</option>\n  </select>\n  <p>你好，{{ username }}</p>\n</template>", usage_context: ["表单输入", "搜索框", "设置面板", "自定义组件双向绑定"], common_mistakes: ["在非表单元素上使用无效", "自定义组件需要 modelValue + update:modelValue", "v-model 修饰符（.lazy .number .trim）遗忘"] },
  { keyword: "setup", language: "vue", category: "Vue", definition: "Vue 3 组件选项/<script setup> 语法糖，Composition API 的入口。\nVue 3 component option / <script setup> syntax sugar; entry point for Composition API.", code_example: "<script setup>\nimport { ref, computed } from 'vue';\n\nconst count = ref(0);\nconst doubled = computed(() => count.value * 2);\n\nfunction increment() {\n  count.value++;\n}\n</script>\n\n<template>\n  <button @click=\"increment\">{{ doubled }}</button>\n</template>", usage_context: ["Vue 3 组件编写", "组合式 API 入口", "自动注册导入的组件"], common_mistakes: ["<script setup> 中顶层变量自动暴露，不需 return", "不能使用 this", "与 Options API 混用时的优先级问题"] },

  // ── Python 补充 ──
  { keyword: "match", language: "python", category: "控制流", definition: "结构模式匹配（Python 3.10+），类似 switch-case 但更强大。\nStructural pattern matching (Python 3.10+), similar to switch-case but more powerful.", code_example: "match command:\n    case \"quit\":\n        exit()\n    case \"hello\":\n        print(\"你好\")\n    case _:\n        print(\"未知命令\")", usage_context: ["命令解析", "状态机", "数据结构解构"], common_mistakes: ["Python 3.10 以下版本不支持", "忘记通配符 _ 分支", "模式匹配不是简单的值比较"] },

  // ── JavaScript 补充 ──
  { keyword: "for...of", language: "javascript", category: "控制流", definition: "遍历可迭代对象（Array、String、Map、Set 等）的值。\nIterates over values of iterable objects.", code_example: "const arr = [10, 20, 30];\nfor (const val of arr) {\n  console.log(val); // 10, 20, 30\n}\n\nfor (const ch of \"hello\") {\n  console.log(ch); // h, e, l, l, o\n}", usage_context: ["遍历数组值", "遍历字符串字符", "遍历 Map/Set"], common_mistakes: ["与 for...in 混淆（in 遍历键，of 遍历值）", "普通对象不能用 for...of 遍历"] },
  { keyword: "for...in", language: "javascript", category: "控制流", definition: "遍历对象的可枚举属性键名。\nIterates over enumerable property keys of an object.", code_example: "const obj = { a: 1, b: 2, c: 3 };\nfor (const key in obj) {\n  console.log(key, obj[key]); // a 1, b 2, c 3\n}", usage_context: ["遍历对象属性", "检查对象有哪些键"], common_mistakes: ["遍历数组时得到的是索引字符串", "会遍历原型链上的属性", "遍历数组应用 for...of"] },
  { keyword: "function*", language: "javascript", category: "函数", definition: "生成器函数，使用 yield 暂停和恢复执行，返回迭代器。\nGenerator function; uses yield to pause/resume execution, returns an iterator.", code_example: "function* counter() {\n  let i = 0;\n  while (true) {\n    yield i++;\n  }\n}\n\nconst gen = counter();\ngen.next(); // { value: 0, done: false }\ngen.next(); // { value: 1, done: false }", usage_context: ["惰性求值", "无限序列", "异步流程控制", "实现可迭代协议"], common_mistakes: ["忘记 function 后面的 *", "生成器函数不会立即执行", "yield 只能在生成器函数内使用"] },
  { keyword: "Proxy", language: "javascript", category: "数据类型", definition: "创建对象的代理，拦截并自定义基本操作（读取、赋值、函数调用等）。\nCreates a proxy for an object, intercepting fundamental operations.", code_example: "const handler = {\n  get(target, prop) {\n    console.log(`读取 ${prop}`);\n    return prop in target ? target[prop] : undefined;\n  }\n};\n\nconst proxy = new Proxy({ name: \"Alice\" }, handler);\nproxy.name; // 日志: 读取 name → \"Alice\"", usage_context: ["数据绑定", "表单验证", "日志/调试", "Vue 3 响应式原理"], common_mistakes: ["代理不可撤销时无法解除", "this 指向代理对象而非原始对象", "性能开销不适合高频操作"] },
  { keyword: "WeakMap", language: "javascript", category: "数据类型", definition: "键必须是对象的弱引用 Map，键被垃圾回收时自动移除条目。\nMap with object-only keys that are weakly referenced; entries auto-removed when keys are GC'd.", code_example: "const wm = new WeakMap();\nlet obj = { data: \"secret\" };\nwm.set(obj, 42);\nconsole.log(wm.get(obj)); // 42\n\nobj = null; // 条目会被垃圾回收", usage_context: ["存储对象的私有数据", "DOM 元素关联数据", "缓存计算结果"], common_mistakes: ["不能遍历（无 forEach/size）", "键必须是对象", "弱引用意味着键可能随时消失"] },
  { keyword: "Promise.all", language: "javascript", category: "异步", definition: "并行执行多个 Promise，全部完成后返回结果数组；任一失败则立即失败。\nRuns multiple Promises in parallel; resolves with array of results, rejects on first failure.", code_example: "const p1 = fetch(\"/api/users\");\nconst p2 = fetch(\"/api/posts\");\nconst [users, posts] = await Promise.all([\n  p1.then(r => r.json()),\n  p2.then(r => r.json())\n]);", usage_context: ["并行 API 请求", "批量操作", "加速异步任务"], common_mistakes: ["一个失败全部失败（用 Promise.allSettled 获取所有结果）", "不是真正的并行（仍是单线程）", "数组顺序与传入顺序一致"] },
  { keyword: "??=", language: "javascript", category: "运算符", definition: "空值赋值运算符，仅当变量为 null 或 undefined 时赋值。\nNullish assignment; assigns only when the variable is null/undefined.", code_example: "let config = { port: 3000 };\nconfig.port ??= 8080;   // 不变，3000\nconfig.host ??= \"localhost\"; // 赋值，localhost", usage_context: ["默认值设置", "配置合并", "避免覆盖已有值"], common_mistakes: ["与 ||= 混淆（||= 对 0 和 '' 也会赋值）", "只有 null/undefined 触发赋值"] },

  // ── React 补充 ──
  { keyword: "useCallback", language: "react", category: "React", definition: "React Hook，缓存函数引用，避免子组件因回调函数变化而不必要重渲染。\nReact Hook that memoizes a function reference to prevent unnecessary re-renders.", code_example: "import { useCallback, useState } from 'react';\n\nfunction Parent() {\n  const [count, setCount] = useState(0);\n  const handleClick = useCallback(() => {\n    setCount(c => c + 1);\n  }, []); // 依赖为空，函数引用稳定\n  return <Child onClick={handleClick} />;\n}", usage_context: ["传递给子组件的回调", "作为 useEffect 依赖", "性能优化"], common_mistakes: ["依赖数组遗漏导致闭包陷阱", "过度使用反而增加复杂度", "不配合 React.memo 使用则无意义"] },
  { keyword: "useMemo", language: "react", category: "React", definition: "React Hook，缓存计算结果，仅在依赖变化时重新计算。\nReact Hook that memoizes a computed value, recalculates only when dependencies change.", code_example: "import { useMemo } from 'react';\n\nfunction ProductList({ products, query }) {\n  const filtered = useMemo(\n    () => products.filter(p => p.name.includes(query)),\n    [products, query]\n  );\n  return filtered.map(p => <div key={p.id}>{p.name}</div>);\n}", usage_context: ["昂贵的过滤/排序计算", "派生数据", "避免每次渲染重复计算"], common_mistakes: ["依赖数组不正确导致过时数据", "简单计算不值得 memo 化", "不是所有值都需要 useMemo"] },
  { keyword: "memo", language: "react", category: "React", definition: "React 高阶组件，缓存组件渲染结果，仅在 props 变化时重渲染。\nReact HOC that caches render output; re-renders only when props change.", code_example: "import { memo } from 'react';\n\nconst ExpensiveList = memo(function ExpensiveList({ items }) {\n  console.log('rendered');\n  return items.map(i => <div key={i}>{i}</div>);\n});\n// 父组件重渲染时，items 不变则 ExpensiveList 不重渲染", usage_context: ["优化列表项组件", "避免父组件更新导致子组件无意义重渲染", "配合 useCallback/useMemo 使用"], common_mistakes: ["props 是对象/数组时引用变化导致 memo 失效", "过度 memo 化反而浪费内存", "不解决渲染逻辑本身的问题"] },
  { keyword: "useReducer", language: "react", category: "React", definition: "React Hook，使用 reducer 函数管理复杂状态逻辑，类似 Redux 模式。\nReact Hook for complex state logic using a reducer function, similar to Redux pattern.", code_example: "import { useReducer } from 'react';\n\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'increment': return { count: state.count + 1 };\n    case 'decrement': return { count: state.count - 1 };\n    default: return state;\n  }\n}\n\nfunction Counter() {\n  const [state, dispatch] = useReducer(reducer, { count: 0 });\n  return <button onClick={() => dispatch({ type: 'increment' })}>{state.count}</button>;\n}", usage_context: ["复杂表单状态", "多操作状态管理", "替代多个 useState"], common_mistakes: ["简单场景不需要用 useReducer", "reducer 必须是纯函数", "忘记返回新状态对象"] },
  { keyword: "Suspense", language: "react", category: "React", definition: "React 组件，在子组件加载时显示 fallback 内容。\nReact component that shows fallback content while children are loading.", code_example: "import { Suspense, lazy } from 'react';\n\nconst Dashboard = lazy(() => import('./Dashboard'));\n\nfunction App() {\n  return (\n    <Suspense fallback={<div>加载中...</div>}>\n      <Dashboard />\n    </Suspense>\n  );\n}", usage_context: ["代码分割加载", "数据加载占位", "配合 React.lazy 使用"], common_mistakes: ["必须配合 lazy() 或数据框架使用", "fallback 组件会闪烁", "错误处理需要 Error Boundary 包裹"] },
  { keyword: "createContext", language: "react", category: "React", definition: "创建 Context 对象，用于跨组件层级共享数据而无需逐层传递 props。\nCreates a Context object for sharing data across component tree without prop drilling.", code_example: "import { createContext, useContext } from 'react';\n\nconst ThemeContext = createContext('light');\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nfunction Toolbar() {\n  const theme = useContext(ThemeContext); // 'dark'\n  return <div className={theme}>Toolbar</div>;\n}", usage_context: ["全局主题/语言", "用户认证状态", "避免 prop drilling"], common_mistakes: ["Context 值变化导致所有消费者重渲染", "不要用 Context 管理频繁变化的值", "忘记 Provider 包裹时使用默认值"] },

  // ── Vue 补充 ──
  { keyword: "v-show", language: "vue", category: "Vue", definition: "Vue 指令，通过 CSS display 属性切换元素可见性（不移除 DOM）。\nVue directive; toggles visibility via CSS display (does not remove DOM).", code_example: "<template>\n  <div v-show=\"isVisible\">我始终存在于 DOM 中</div>\n</template>", usage_context: ["频繁切换显示/隐藏", "不需要销毁重建的场景", "Tab 面板切换"], common_mistakes: ["与 v-if 混淆（v-show 始终渲染 DOM）", "不支持 <template> 元素", "初始渲染开销比 v-if 高"] },
  { keyword: "v-bind", language: "vue", category: "Vue", definition: "Vue 指令，动态绑定 HTML 属性到表达式，缩写为 :attr。\nVue directive; dynamically binds HTML attributes to expressions, shorthand :attr.", code_example: "<template>\n  <img :src=\"imageUrl\" :alt=\"description\" />\n  <div :class=\"{ active: isActive }\" :style=\"{ color: textColor }\" />\n</template>", usage_context: ["动态图片/链接", "条件样式", "绑定任意 HTML 属性"], common_mistakes: ["忘记 : 号会当作字符串", "绑定对象时 key 不能有连字符（需 camelCase）"] },
  { keyword: "v-on", language: "vue", category: "Vue", definition: "Vue 指令，绑定事件监听器，缩写为 @event。\nVue directive; binds event listeners, shorthand @event.", code_example: "<template>\n  <button @click=\"handleClick\">点击</button>\n  <input @keyup.enter=\"submit\" />\n  <form @submit.prevent=\"onSubmit\" />\n</template>", usage_context: ["按钮点击", "表单提交", "键盘事件", "修饰符链式调用"], common_mistakes: ["内联表达式中 this 指向问题", "修饰符顺序有意义（.prevent.self ≠ .self.prevent）"] },
  { keyword: "onMounted", language: "vue", category: "Vue", definition: "Vue 3 Composition API 生命周期钩子，在组件挂载到 DOM 后执行。\nVue 3 lifecycle hook; runs after component is mounted to DOM.", code_example: "import { onMounted, ref } from 'vue';\n\nconst list = ref([]);\nonMounted(async () => {\n  const res = await fetch('/api/items');\n  list.value = await res.json();\n});", usage_context: ["API 数据获取", "DOM 操作", "第三方库初始化"], common_mistakes: ["在 SSR 中不保证执行（用 onMounted 前检查环境）", "多个 onMounted 会按顺序全部执行"] },
  { keyword: "props", language: "vue", category: "Vue", definition: "Vue 组件的输入属性，父组件通过模板传递，子组件只读。\nVue component input properties; passed from parent via template, read-only in child.", code_example: "<script setup>\nconst props = defineProps({\n  title: { type: String, required: true },\n  count: { type: Number, default: 0 }\n});\n</script>\n\n<template>\n  <h1>{{ title }} ({{ count }})</h1>\n</template>", usage_context: ["父传子数据", "组件配置", "内容分发"], common_mistakes: ["直接修改 props（应用 emit 通知父组件）", "对象/数组 props 是引用类型", "defineProps 不能在普通 <script> 中使用"] },
  { keyword: "emits", language: "vue", category: "Vue", definition: "Vue 组件声明可触发的事件，子组件通过 emit 通知父组件。\nVue component event declaration; child notifies parent via emit.", code_example: "<script setup>\nconst emit = defineEmits(['update', 'delete']);\n\nfunction handleClick() {\n  emit('update', { id: 1, name: 'new' });\n}\n</script>\n\n<template>\n  <button @click=\"handleClick\">更新</button>\n</template>", usage_context: ["子组件通知父组件", "表单提交", "状态变更通知"], common_mistakes: ["事件名应使用 kebab-case", "不声明 emits 也能触发但会有警告", "emit 是同步的"] },
  { keyword: "slots", language: "vue", category: "Vue", definition: "Vue 内容分发机制，允许父组件向子组件传递 HTML 内容。\nVue content distribution mechanism; allows parent to pass HTML content to child.", code_example: "<!-- 子组件 Card.vue -->\n<template>\n  <div class=\"card\">\n    <slot name=\"header\" />\n    <slot>默认内容</slot>\n    <slot name=\"footer\" />\n  </div>\n</template>\n\n<!-- 父组件 -->\n<Card>\n  <template #header><h2>标题</h2></template>\n  <p>正文内容</p>\n  <template #footer><button>确定</button></template>\n</Card>", usage_context: ["布局组件", "可复用的容器", "自定义弹窗/卡片内容"], common_mistakes: ["作用域插槽需要 v-slot 或 #slotName=\"{ data }\"", "slot 内容在父组件作用域中编译"] },
  { keyword: "provide", language: "vue", category: "Vue", definition: "Vue 3 Composition API，向所有后代组件提供数据（依赖注入的提供端）。\nVue 3 Composition API; provides data to all descendant components (dependency injection provider).", code_example: "import { provide, ref } from 'vue';\n\n// 祖先组件\nconst theme = ref('dark');\nprovide('theme', theme); // 提供响应式引用\n\n// 后代组件\nimport { inject } from 'vue';\nconst theme = inject('theme', 'light'); // 第二个参数是默认值", usage_context: ["跨层级共享数据", "替代深层 prop drilling", "插件/库开发"], common_mistakes: ["provide/inject 不是响应式的（除非传 ref）", "与 React Context 类似但机制不同", "不要过度使用导致数据流不清晰"] },

  // ── Python 补充 ──
  { keyword: ":=", language: "python", category: "运算符", definition: "海象运算符（Python 3.8+），在表达式中赋值，避免重复计算。\nWalrus operator (Python 3.8+); assigns value within an expression.", code_example: "# 不用海象运算符\nline = input()\nwhile line != 'quit':\n    print(line)\n    line = input()\n\n# 用海象运算符\nwhile (line := input()) != 'quit':\n    print(line)", usage_context: ["while 循环条件中赋值", "列表推导式中复用计算结果", "正则匹配中提取组"], common_mistakes: ["Python 3.8 以下不支持", "需要括号包裹以明确优先级", "过度使用降低可读性"] },

  // ── JavaScript 补充 ──
  { keyword: "JSON", language: "javascript", category: "数据类型", definition: "内置对象，提供 JSON 数据的解析和序列化方法。\nBuilt-in object for parsing and stringifying JSON data.", code_example: "const str = '{\"name\":\"Alice\",\"age\":30}';\nconst obj = JSON.parse(str);\nconsole.log(obj.name); // Alice\n\nconst back = JSON.stringify(obj, null, 2);", usage_context: ["API 响应解析", "数据持久化", "深拷贝（简单对象）", "调试输出"], common_mistakes: ["JSON.parse 非法字符串会抛异常", "JSON.stringify 会丢失 undefined/函数", "循环引用会报错"] },
  { keyword: "console", language: "javascript", category: "数据类型", definition: "内置对象，提供调试输出方法（log、warn、error、table 等）。\nBuilt-in object for debug output (log, warn, error, table, etc.).", code_example: "console.log('普通日志');\nconsole.warn('警告');\nconsole.error('错误');\nconsole.table([{ name: 'Alice', age: 30 }]);\nconsole.time('计时');\n// ... 操作\nconsole.timeEnd('计时');", usage_context: ["调试输出", "性能计时", "数据结构可视化"], common_mistakes: ["生产环境应移除或替换为日志库", "console.log 对象是引用（可能看到修改后的值）", "console.table 对大数组很慢"] },

  // ── React 补充 ──
  { keyword: "useLayoutEffect", language: "react", category: "React", definition: "React Hook，与 useEffect 相同时机但同步执行，在浏览器绘制前触发。\nReact Hook; same as useEffect but fires synchronously before browser paint.", code_example: "import { useLayoutEffect, useRef, useState } from 'react';\n\nfunction Tooltip({ targetRef, text }) {\n  const tooltipRef = useRef(null);\n  const [pos, setPos] = useState({ top: 0, left: 0 });\n\n  useLayoutEffect(() => {\n    const rect = targetRef.current.getBoundingClientRect();\n    setPos({ top: rect.bottom, left: rect.left });\n  }, [targetRef]);\n\n  return <div ref={tooltipRef} style={{ position: 'fixed', ...pos }}>{text}</div>;\n}", usage_context: ["DOM 测量（getBoundingClientRect）", "避免闪烁的布局调整", "同步读取 DOM 样式"], common_mistakes: ["会阻塞渲染，影响性能", "大多数场景用 useEffect 就够了", "SSR 中会警告"] },
  { keyword: "useImperativeHandle", language: "react", category: "React", definition: "React Hook，配合 forwardRef 自定义暴露给父组件的 ref 方法。\nReact Hook; customizes the instance value exposed to parent via ref (used with forwardRef).", code_example: "import { useRef, useImperativeHandle, forwardRef } from 'react';\n\nconst Input = forwardRef((props, ref) => {\n  const inputRef = useRef(null);\n  useImperativeHandle(ref, () => ({\n    focus: () => inputRef.current.focus(),\n    clear: () => { inputRef.current.value = ''; }\n  }));\n  return <input ref={inputRef} />;\n});\n\n// 父组件\nconst ref = useRef();\nref.current.focus(); // 只暴露 focus 和 clear", usage_context: ["封装组件暴露有限方法", "表单组件的命令式 API", "避免暴露整个 DOM 节点"], common_mistakes: ["必须配合 forwardRef 使用", "依赖数组控制何时重建暴露的方法", "尽量少用，优先用声明式 props"] },
  { keyword: "forwardRef", language: "react", category: "React", definition: "React 高阶组件，将 ref 转发传递给子组件的 DOM 节点或自定义方法。\nReact HOC; forwards ref to a child component's DOM node or custom imperative handle.", code_example: "import { forwardRef, useRef } from 'react';\n\nconst FancyButton = forwardRef((props, ref) => (\n  <button ref={ref} className=\"fancy\" {...props} />\n));\n\n// 父组件可以直接访问 button DOM\nconst ref = useRef();\n<FancyButton ref={ref}>Click</FancyButton>\nref.current.focus();", usage_context: ["需要直接操作子组件 DOM", "与 useImperativeHandle 配合", "库/组件开发"], common_mistakes: ["React 19 中 ref 直接作为 prop，不再需要 forwardRef", "forwardRef 会增加组件层级", "不要过度使用，大多数场景不需要"] },
  { keyword: "Fragment", language: "react", category: "React", definition: "React 组件，允许返回多个元素而无需额外 DOM 包装节点。\nReact component; allows returning multiple elements without extra DOM wrapper.", code_example: "import { Fragment } from 'react';\n\nfunction Columns() {\n  return (\n    <Fragment>\n      <td>A</td>\n      <td>B</td>\n    </Fragment>\n  );\n}\n\n// 简写语法\nfunction Columns() {\n  return (\n    <>\n      <td>A</td>\n      <td>B</td>\n    </>\n  );\n}", usage_context: ["表格行列结构", "避免多余 DOM 节点", "列表渲染返回多个元素"], common_mistakes: ["<> 简写不能接受 key 属性", "需要用 <Fragment key={...}> 的形式", "不影响渲染结果，只是语法糖"] },
  { keyword: "key", language: "react", category: "React", definition: "React 特殊属性，用于标识列表中的元素，帮助 Diff 算法高效更新。\nReact special prop; identifies elements in a list for efficient diffing.", code_example: "function TodoList({ items }) {\n  return (\n    <ul>\n      {items.map(item => (\n        <li key={item.id}>{item.text}</li>\n      ))}\n    </ul>\n  );\n}", usage_context: ["列表渲染", "动态组件切换", "避免列表重排问题"], common_mistakes: ["不要用数组 index 作为 key（会导致状态错乱）", "key 只在兄弟节点间唯一", "key 不会作为 prop 传递给组件"] },

  // ── Vue 补充 ──
  { keyword: "v-slot", language: "vue", category: "Vue", definition: "Vue 指令，声明具名插槽或作用域插槽，缩写为 #name。\nVue directive; declares named or scoped slots, shorthand #name.", code_example: "<!-- 子组件 -->\n<slot name=\"header\" :data=\"items\"></slot>\n\n<!-- 父组件 -->\n<template #header=\"{ data }\">\n  <h2>{{ data.length }} 项</h2>\n</template>", usage_context: ["具名插槽", "作用域插槽传数据", "组件内容分发"], common_mistakes: ["#header 是 v-slot:header 的缩写", "作用域插槽解构在父组件作用域", "动态插槽名用 v-slot:[dynamicName]"] },
  { keyword: "v-once", language: "vue", category: "Vue", definition: "Vue 指令，元素/组件只渲染一次，后续数据变化不再更新。\nVue directive; renders the element/component only once, ignores subsequent data changes.", code_example: "<template>\n  <p v-once>这个标题不会变：{{ title }}</p>\n  <p>这个会变：{{ title }}</p>\n</template>", usage_context: ["静态内容优化", "不需要更新的纯展示文本", "大量静态节点的性能优化"], common_mistakes: ["整个子树都不会更新", "与 v-if/v-for 同用时有特殊行为", "不要用在需要响应式更新的元素上"] },
  { keyword: "v-pre", language: "vue", category: "Vue", definition: "Vue 指令，跳过该元素及其子元素的编译，原样输出 Mustache 语法。\nVue directive; skips compilation for the element and its children, outputs raw Mustache syntax.", code_example: "<template>\n  <span v-pre>{{ 这不会被编译 }}</span>\n</template>", usage_context: ["展示原始模板语法", "文档/教程中显示 Vue 语法", "跳过大量静态内容的编译"], common_mistakes: ["子元素中的 Vue 指令都不会生效", "不需要响应式的纯 HTML 块可以用来优化"] },
  { keyword: "v-cloak", language: "vue", category: "Vue", definition: "Vue 指令，在组件编译完成前保持元素隐藏，防止闪烁未编译的模板。\nVue directive; keeps element hidden until compilation is done, prevents flash of uncompiled template.", code_example: "<style>\n[v-cloak] { display: none; }\n</style>\n\n<template>\n  <div v-cloak>{{ message }}</div>\n</template>", usage_context: ["防止页面闪烁 {{ 变量名 }}", "配合 CSS 使用", "Vue 2 项目常见"], common_mistakes: ["必须配合 CSS [v-cloak] { display: none }", "Vue 3 + Vite 通常不需要（编译足够快）", "只在手动挂载时有意义"] },
  { keyword: "onUpdated", language: "vue", category: "Vue", definition: "Vue 3 生命周期钩子，在组件因响应式状态变化而重新渲染后执行。\nVue 3 lifecycle hook; runs after component re-renders due to reactive state change.", code_example: "import { onUpdated, ref } from 'vue';\n\nconst count = ref(0);\nonUpdated(() => {\n  console.log('DOM 已更新，count:', count.value);\n});", usage_context: ["DOM 更新后操作", "依赖更新后的副作用", "调试渲染时机"], common_mistakes: ["不要在回调中修改响应式状态（会死循环）", "子组件更新也会触发父组件的 onUpdated", "首次渲染不触发（用 onMounted）"] },
  { keyword: "onUnmounted", language: "vue", category: "Vue", definition: "Vue 3 生命周期钩子，在组件实例卸载后执行，用于清理副作用。\nVue 3 lifecycle hook; runs after component instance is unmounted, used for cleanup.", code_example: "import { onMounted, onUnmounted } from 'vue';\n\nlet timer;\nonMounted(() => {\n  timer = setInterval(() => console.log('tick'), 1000);\n});\nonUnmounted(() => {\n  clearInterval(timer);\n});", usage_context: ["清除定时器", "移除事件监听", "断开 WebSocket", "取消订阅"], common_mistakes: ["忘记清理导致内存泄漏", "组件卸载后不应再更新状态", "与 beforeUnmount 的区别（卸载前 vs 卸载后）"] },
  { keyword: "defineExpose", language: "vue", category: "Vue", definition: "Vue 3 <script setup> 编译器宏，显式声明组件暴露给父组件的属性/方法。\nVue 3 <script setup> compiler macro; explicitly declares which properties/methods to expose to parent.", code_example: "<script setup>\nimport { ref } from 'vue';\n\nconst inputRef = ref(null);\nconst count = ref(0);\n\nfunction reset() {\n  count.value = 0;\n}\n\ndefineExpose({ count, reset });\n// 父组件通过 ref 只能访问 count 和 reset\n</script>", usage_context: ["控制组件暴露的公共 API", "配合父组件 ref 使用", "封装内部实现细节"], common_mistakes: ["<script setup> 默认不暴露任何东西", "不使用 defineExpose 则父组件 ref 为空对象", "只暴露必要的属性/方法"] },
  { keyword: "nextTick", language: "vue", category: "Vue", definition: "Vue 工具函数，在下次 DOM 更新刷新后执行回调。\nVue utility; executes a callback after the next DOM update flush.", code_example: "import { ref, nextTick } from 'vue';\n\nconst message = ref('旧值');\nmessage.value = '新值';\n\n// 此时 DOM 还没更新\nawait nextTick();\n// 现在 DOM 已经更新了\nconsole.log(document.getElementById('msg').textContent); // '新值'", usage_context: ["等待 DOM 更新后操作", "获取更新后的元素尺寸", "连续修改后统一 DOM 更新"], common_mistakes: ["不要用 setTimeout 代替 nextTick", "nextTick 返回 Promise，可以 await", "在 nextTick 前多次修改同一属性只会触发一次更新"] },

  // ── NestJS ──
  { keyword: "@Module", language: "nestjs", category: "NestJS", definition: "装饰器，定义一个模块，组织相关的控制器、服务等组件。\nDecorator that defines a module, organizing related controllers, services, and other components.", code_example: "import { Module } from '@nestjs/common';\nimport { CatsController } from './cats.controller';\nimport { CatsService } from './cats.service';\n\n@Module({\n  controllers: [CatsController],\n  providers: [CatsService],\n  exports: [CatsService],\n})\nexport class CatsModule {}", usage_context: ["组织应用结构", "模块化代码", "控制依赖可见性"], common_mistakes: ["忘记导入使用到的模块", "providers 只在模块内可见（需 exports 暴露）", "循环模块依赖需要用 forwardRef"] },
  { keyword: "@Controller", language: "nestjs", category: "NestJS", definition: "装饰器，定义一个控制器，处理 HTTP 请求并返回响应。\nDecorator that defines a controller handling HTTP requests and returning responses.", code_example: "import { Controller, Get, Post, Body } from '@nestjs/common';\n\n@Controller('cats')\nexport class CatsController {\n  @Get()\n  findAll() {\n    return 'all cats';\n  }\n\n  @Post()\n  create(@Body() createCatDto: CreateCatDto) {\n    return 'created';\n  }\n}", usage_context: ["定义 REST API 端点", "处理 HTTP 请求", "路由分组"], common_mistakes: ["路由前缀是字符串不是路径", "忘记注册到模块的 controllers 数组", "控制器不应包含业务逻辑（交给 Service）"] },
  { keyword: "@Injectable", language: "nestjs", category: "NestJS", definition: "装饰器，标记类为可注入的提供者，可通过依赖注入使用。\nDecorator that marks a class as an injectable provider for dependency injection.", code_example: "import { Injectable } from '@nestjs/common';\n\n@Injectable()\nexport class CatsService {\n  private readonly cats: Cat[] = [];\n\n  findAll(): Cat[] {\n    return this.cats;\n  }\n\n  create(cat: Cat) {\n    this.cats.push(cat);\n  }\n}", usage_context: ["服务层业务逻辑", "数据访问层", "可复用的工具类"], common_mistakes: ["忘记 @Injectable 装饰器导致注入失败", "没有注册到模块的 providers 数组", "单例默认行为（同一实例共享）"] },
  { keyword: "@Get", language: "nestjs", category: "NestJS", definition: "HTTP 方法装饰器，将方法绑定为 GET 请求的处理函数。\nHTTP method decorator; binds a method as a GET request handler.", code_example: "@Controller('users')\nexport class UsersController {\n  @Get()\n  findAll() {\n    return this.usersService.findAll();\n  }\n\n  @Get(':id')\n  findOne(@Param('id') id: string) {\n    return this.usersService.findOne(id);\n  }\n}", usage_context: ["查询数据端点", "获取资源列表", "获取单个资源详情"], common_mistakes: ["路由参数用 :param 语法", "多个同方法路由时顺序很重要（具体路由在前）", "返回值自动序列化为 JSON"] },
  { keyword: "@Post", language: "nestjs", category: "NestJS", definition: "HTTP 方法装饰器，将方法绑定为 POST 请求的处理函数。\nHTTP method decorator; binds a method as a POST request handler.", code_example: "@Controller('cats')\nexport class CatsController {\n  @Post()\n  create(@Body() createCatDto: CreateCatDto) {\n    return this.catsService.create(createCatDto);\n  }\n}", usage_context: ["创建资源端点", "提交表单数据", "文件上传"], common_mistakes: ["用 @Body() 获取请求体", "DTO 应配合 ValidationPipe 做校验", "POST 路由不要有副作用之外的返回语义"] },
  { keyword: "@Body", language: "nestjs", category: "NestJS", definition: "参数装饰器，从请求体中提取数据并注入到方法参数。\nParameter decorator; extracts data from the request body and injects it into the method parameter.", code_example: "@Post()\ncreate(@Body() createCatDto: CreateCatDto) {\n  return this.catsService.create(createCatDto);\n}\n\n// 只取特定字段\n@Post()\ncreate(@Body('name') name: string) {\n  return `Created ${name}`;\n}", usage_context: ["接收 POST/PUT 请求体", "接收 JSON 数据", "配合 DTO 做类型转换"], common_mistakes: ["不加参数时注入整个 body", "需要 ValidationPipe 才能自动验证 DTO", "Content-Type 必须是 application/json"] },
  { keyword: "@Param", language: "nestjs", category: "NestJS", definition: "参数装饰器，从 URL 路径参数中提取数据。\nParameter decorator; extracts data from URL path parameters.", code_example: "@Get(':id')\nfindOne(@Param('id') id: string) {\n  return this.catsService.findOne(id);\n}\n\n// 一次性获取所有参数\n@Delete(':id')\nremove(@Param() params: { id: string }) {\n  return this.catsService.remove(params.id);\n}", usage_context: ["RESTful 资源标识", "路由参数提取", "动态路由"], common_mistakes: ["参数始终是字符串（需要手动转换类型）", "用 ParseIntPipe 自动转换数字类型", "路由定义和装饰器参数名要一致"] },
  { keyword: "@Query", language: "nestjs", category: "NestJS", definition: "参数装饰器，从 URL 查询字符串中提取数据。\nParameter decorator; extracts data from URL query string.", code_example: "@Get()\nfindAll(@Query('page') page: number, @Query('limit') limit: number) {\n  return this.catsService.findAll({ page, limit });\n}", usage_context: ["分页参数", "过滤条件", "搜索关键字"], common_mistakes: ["查询参数始终是字符串", "可选参数需设默认值", "配合 DTO 可批量提取和验证"] },
  { keyword: "Provider", language: "nestjs", category: "NestJS", definition: "NestJS 核心概念，被注入的类（通常是 Service），通过依赖注入容器管理。\nNestJS core concept; an injectable class (usually a Service) managed by the DI container.", code_example: "// 提供者注册\n@Module({\n  providers: [\n    CatsService,\n    { provide: 'CONFIG', useValue: { port: 3000 } },\n    { provide: Logger, useClass: CustomLogger },\n  ],\n})\nexport class AppModule {}", usage_context: ["服务注册", "依赖注入配置", "工厂模式", "值注入"], common_mistakes: ["提供者默认是单例", "useClass/useValue/useFactory 用法不同", "自定义提供者需要 useFactory 处理异步初始化"] },
  { keyword: "Guard", language: "nestjs", category: "NestJS", definition: "实现 CanActivate 接口的类，用于身份验证和授权，决定请求是否可以继续。\nClass implementing CanActivate interface; handles authentication and authorization.", code_example: "import { Injectable, CanActivate, ExecutionContext } from '@nestjs/common';\n\n@Injectable()\nexport class AuthGuard implements CanActivate {\n  canActivate(context: ExecutionContext): boolean {\n    const request = context.switchToHttp().getRequest();\n    return validateRequest(request);\n  }\n}\n\n// 使用\n@UseGuards(AuthGuard)\n@Get('profile')\ngetProfile() { ... }", usage_context: ["身份验证", "角色授权", "API 密钥校验", "IP 白名单"], common_mistakes: ["返回 false 则请求被拒绝（403）", "可以用 SetMetadata 自定义元数据", "全局注册用 app.useGlobalGuards()"] },
  { keyword: "Interceptor", language: "nestjs", category: "NestJS", definition: "实现 NestInterceptor 接口的类，在请求前后添加额外逻辑（日志、缓存、响应转换）。\nClass implementing NestInterceptor; adds logic before/after request handling.", code_example: "import { Injectable, NestInterceptor, ExecutionContext, CallHandler } from '@nestjs/common';\nimport { Observable } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\n@Injectable()\nexport class TransformInterceptor implements NestInterceptor {\n  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {\n    return next.handle().pipe(\n      map(data => ({ data, timestamp: Date.now() }))\n    );\n  }\n}", usage_context: ["响应数据转换", "日志记录", "缓存处理", "异常映射", "超时处理"], common_mistakes: ["用 RxJS 操作符处理响应流", "不调用 next.handle() 则请求被拦截", "可以绑定到控制器或全局"] },
  { keyword: "Pipe", language: "nestjs", category: "NestJS", definition: "实现 PipeTransform 接口的类，用于数据转换和验证。\nClass implementing PipeTransform; used for data transformation and validation.", code_example: "import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';\n\n@Injectable()\nexport class ParseIntPipe implements PipeTransform<string, number> {\n  transform(value: string): number {\n    const val = parseInt(value, 10);\n    if (isNaN(val)) {\n      throw new BadRequestException('不是有效数字');\n    }\n    return val;\n  }\n}\n\n// 使用\n@Get(':id')\nfindOne(@Param('id', ParseIntPipe) id: number) { ... }", usage_context: ["参数类型转换", "DTO 验证（配合 class-validator）", "数据清洗", "文件验证"], common_mistakes: ["内置 Pipe: ParseIntPipe, ParseBoolPipe, ValidationPipe", "ValidationPipe 需要 class-validator 和 class-transformer", "抛异常则请求被拦截（400）"] },
  { keyword: "DTO", language: "nestjs", category: "NestJS", definition: "数据传输对象，定义请求/响应的数据结构，配合验证装饰器使用。\nData Transfer Object; defines request/response data structure with validation decorators.", code_example: "import { IsString, IsInt, Min, Max } from 'class-validator';\n\nexport class CreateCatDto {\n  @IsString()\n  name: string;\n\n  @IsInt()\n  @Min(0)\n  @Max(30)\n  age: number;\n\n  @IsString()\n  breed: string;\n}\n\n// 在控制器中使用\n@Post()\ncreate(@Body() dto: CreateCatDto) { ... }", usage_context: ["API 请求体定义", "数据验证", "Swagger 文档生成", "类型安全"], common_mistakes: ["需要 ValidationPipe 才能自动验证", "安装 class-validator 和 class-transformer", "DTO 不是数据库实体（应分开定义）"] },
  { keyword: "@Inject", language: "nestjs", category: "NestJS", definition: "装饰器，手动指定依赖注入的 token（用于非类依赖或自定义提供者）。\nDecorator that manually specifies the injection token for non-class dependencies or custom providers.", code_example: "const CONFIG_TOKEN = 'CONFIG';\n\n@Injectable()\nexport class AppService {\n  constructor(\n    @Inject(CONFIG_TOKEN) private config: { port: number }\n  ) {}\n\n  getPort() {\n    return this.config.port;\n  }\n}", usage_context: ["注入非类依赖（字符串/Symbol token）", "注入配置对象", "注入第三方库实例"], common_mistakes: ["类依赖不需要 @Inject（自动推断）", "token 必须和 providers 中注册的一致", "可以用 useFactory 异步创建依赖"] },
  { keyword: "Middleware", language: "nestjs", category: "NestJS", definition: "在路由处理前执行的函数，用于日志、认证、CORS 等通用逻辑。\nFunction executed before route handling; used for logging, auth, CORS, and other cross-cutting concerns.", code_example: "import { Injectable, NestMiddleware } from '@nestjs/common';\nimport { Request, Response, NextFunction } from 'express';\n\n@Injectable()\nexport class LoggerMiddleware implements NestMiddleware {\n  use(req: Request, res: Response, next: NextFunction) {\n    console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);\n    next();\n  }\n}\n\n// 在模块中配置\nexport class AppModule implements NestModule {\n  configure(consumer: MiddlewareConsumer) {\n    consumer.apply(LoggerMiddleware).forRoutes('*');\n  }\n}", usage_context: ["请求日志", "CORS 处理", "请求预处理", "旧 Express 中间件集成"], common_mistakes: ["必须调用 next() 否则请求会挂起", "中间件在 Guard 之前执行", "可以用 .forRoutes() 限制路由"] },
  { keyword: "ExceptionFilter", language: "nestjs", category: "NestJS", definition: "实现 ExceptionFilter 接口的类，捕获并处理异常，返回自定义错误响应。\nClass implementing ExceptionFilter; catches and handles exceptions with custom error responses.", code_example: "import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';\n\n@Catch(HttpException)\nexport class HttpExceptionFilter implements ExceptionFilter {\n  catch(exception: HttpException, host: ArgumentsHost) {\n    const ctx = host.switchToHttp();\n    const response = ctx.getResponse();\n    const status = exception.getStatus();\n\n    response.status(status).json({\n      statusCode: status,\n      message: exception.message,\n      timestamp: new Date().toISOString(),\n    });\n  }\n}", usage_context: ["统一错误响应格式", "异常日志记录", "特定异常类型处理", "全局错误处理"], common_mistakes: ["@Catch() 不传参数则捕获所有异常", "全局注册用 app.useGlobalFilters()", "过滤器在拦截器之后执行"] },

  // ── NestJS HTTP 方法 ──
  { keyword: "@Put", language: "nestjs", category: "NestJS", definition: "HTTP 方法装饰器，将方法绑定为 PUT 请求的处理函数（完整更新）。\nHTTP method decorator; binds a method as a PUT request handler (full update).", code_example: "@Put(':id')\nupdate(@Param('id') id: string, @Body() updateCatDto: UpdateCatDto) {\n  return this.catsService.update(id, updateCatDto);\n}", usage_context: ["完整资源更新", "替换已有数据"], common_mistakes: ["PUT 是完整替换，PATCH 是部分更新", "需要返回更新后的资源或 204"] },
  { keyword: "@Delete", language: "nestjs", category: "NestJS", definition: "HTTP 方法装饰器，将方法绑定为 DELETE 请求的处理函数。\nHTTP method decorator; binds a method as a DELETE request handler.", code_example: "@Delete(':id')\nremove(@Param('id') id: string) {\n  return this.catsService.remove(id);\n}", usage_context: ["删除资源", "批量删除"], common_mistakes: ["通常返回 204 No Content", "软删除应返回更新后的资源", "注意级联删除的影响"] },
  { keyword: "@Patch", language: "nestjs", category: "NestJS", definition: "HTTP 方法装饰器，将方法绑定为 PATCH 请求的处理函数（部分更新）。\nHTTP method decorator; binds a method as a PATCH request handler (partial update).", code_example: "@Patch(':id')\nupdate(@Param('id') id: string, @Body() updateCatDto: UpdateCatDto) {\n  return this.catsService.update(id, updateCatDto);\n}", usage_context: ["部分资源更新", "只修改指定字段"], common_mistakes: ["PATCH 是部分更新，PUT 是完整替换", "DTO 字段应全部可选（PartialType）"] },

  // ── NestJS 参数装饰器 ──
  { keyword: "@Headers", language: "nestjs", category: "NestJS", definition: "参数装饰器，从请求头中提取数据。\nParameter decorator; extracts data from request headers.", code_example: "(@Headers('authorization') auth: string) {\n  return this.authService.validateToken(auth);\n}\n\n// 获取所有 headers\n(@Headers() headers: Record<string, string>) {\n  return headers;\n}", usage_context: ["认证 Token 提取", "自定义请求头", "Content-Type 检查"], common_mistakes: ["header 名不区分大小写", "不传参数则获取整个 headers 对象", "某些 header 可能不存在"] },
  { keyword: "@Req", language: "nestjs", category: "NestJS", definition: "参数装饰器，注入底层 HTTP 请求对象（Express/ Fastify Request）。\nParameter decorator; injects the underlying HTTP request object.", code_example: "import { Req } from '@nestjs/common';\nimport { Request } from 'express';\n\n@Get()\nfindAll(@Req() req: Request) {\n  console.log(req.ip, req.hostname);\n  return this.catsService.findAll();\n}", usage_context: ["访问底层请求对象", "获取 IP/域名", "Express/Fastify 特有功能"], common_mistakes: ["通常用 @Body/@Param/@Query 更方便", "类型取决于底层平台（Express.Request vs Fastify.Request）"] },
  { keyword: "@Res", language: "nestjs", category: "NestJS", definition: "参数装饰器，注入底层 HTTP 响应对象，可自定义响应行为。\nParameter decorator; injects the underlying HTTP response object for custom responses.", code_example: "import { Res } from '@nestjs/common';\nimport { Response } from 'express';\n\n@Get()\nfindAll(@Res() res: Response) {\n  res.status(200).json({ data: 'custom response' });\n}", usage_context: ["自定义响应头", "文件下载/流式响应", "重定向"], common_mistakes: ["注入 @Res 后 NestJS 不再自动处理响应", "必须手动调用 res.send/json/end", "可加 @Res({ passthrough: true }) 保持自动处理"] },
  { keyword: "@Session", language: "nestjs", category: "NestJS", definition: "参数装饰器，从请求会话中提取数据（需配置 session 中间件）。\nParameter decorator; extracts data from the request session (requires session middleware).", code_example: "@Get('profile')\ngetProfile(@Session() session: Record<string, any>) {\n  return session.user;\n}\n\n@Post('login')\nlogin(@Session() session: Record<string, any>, @Body() dto: LoginDto) {\n  session.user = dto.username;\n  return 'logged in';\n}", usage_context: ["用户会话管理", "登录状态保持", "购物车等临时数据"], common_mistakes: ["需要安装并配置 express-session", "session 数据存储在服务端", "生产环境应使用 Redis 等外部存储"] },

  // ── NestJS 方法级装饰器 ──
  { keyword: "@UseGuards", language: "nestjs", category: "NestJS", definition: "方法/控制器级装饰器，将 Guard 应用到指定路由或控制器。\nMethod/controller decorator; applies a Guard to specified routes or controller.", code_example: "@UseGuards(AuthGuard)\n@Controller('cats')\nexport class CatsController {\n  @Get()\n  findAll() { ... } // 受 AuthGuard 保护\n\n  @UseGuards(RolesGuard)\n  @Delete(':id')\n  remove() { ... } // 受 AuthGuard + RolesGuard 双重保护\n}", usage_context: ["身份验证", "角色授权", "API 密钥校验"], common_mistakes: ["控制器级 vs 方法级的作用范围", "多个 Guard 按顺序执行", "可用 @SetMetadata 配合 Guard 读取元数据"] },
  { keyword: "@UseInterceptors", language: "nestjs", category: "NestJS", definition: "方法/控制器级装饰器，将 Interceptor 应用到指定路由或控制器。\nMethod/controller decorator; applies an Interceptor to specified routes or controller.", code_example: "@UseInterceptors(TransformInterceptor, LoggingInterceptor)\n@Controller('cats')\nexport class CatsController {\n  @UseInterceptors(CacheInterceptor)\n  @Get()\n  findAll() { ... }\n}", usage_context: ["响应数据转换", "日志记录", "缓存", "超时控制"], common_mistakes: ["多个 Interceptor 按顺序执行", "拦截器在 Pipe 之后、Filter 之前", "可以用 @Exclude() 排除特定路由"] },
  { keyword: "@UsePipes", language: "nestjs", category: "NestJS", definition: "方法/控制器级装饰器，将 Pipe 应用到指定路由或控制器的参数。\nMethod/controller decorator; applies a Pipe to parameters of specified routes.", code_example: "@UsePipes(new ValidationPipe({ transform: true }))\n@Controller('cats')\nexport class CatsController {\n  @Post()\n  create(@Body() createCatDto: CreateCatDto) { ... }\n}", usage_context: ["全局 DTO 验证", "参数类型转换", "数据清洗"], common_mistakes: ["ValidationPipe 需要 class-validator", "transform: true 自动转换类型", "全局注册用 app.useGlobalPipes()"] },
  { keyword: "@UseFilters", language: "nestjs", category: "NestJS", definition: "方法/控制器级装饰器，将 ExceptionFilter 应用到指定路由或控制器。\nMethod/controller decorator; applies an ExceptionFilter to specified routes.", code_example: "@UseFilters(HttpExceptionFilter)\n@Controller('cats')\nexport class CatsController {\n  @Get()\n  findAll() { ... }\n}", usage_context: ["自定义错误响应", "控制器级错误处理", "特定路由的异常处理"], common_mistakes: ["过滤器在拦截器之后执行", "可以堆叠多个过滤器", "全局注册用 app.useGlobalFilters()"] },

  // ── NestJS 架构概念 ──
  { keyword: "ExecutionContext", language: "nestjs", category: "NestJS", definition: "执行上下文对象，提供当前请求的详细信息，Guard 和 Interceptor 中常用。\nExecution context object; provides current request details, commonly used in Guards and Interceptors.", code_example: "import { ExecutionContext } from '@nestjs/common';\n\n@Injectable()\nexport class RolesGuard implements CanActivate {\n  canActivate(context: ExecutionContext): boolean {\n    const request = context.switchToHttp().getRequest();\n    const handler = context.getHandler();\n    const className = context.getClass();\n    return true;\n  }\n}", usage_context: ["Guard 中获取请求", "Interceptor 中获取处理器信息", "反射元数据"], common_mistakes: ["switchToHttp/getHandler/getClass 三种模式", "可以获取方法上的元数据（配合 Reflector）"] },
  { keyword: "HttpException", language: "nestjs", category: "NestJS", definition: "内置异常基类，抛出 HTTP 错误响应。常用子类：NotFoundException、BadRequestException 等。\nBuilt-in exception base class for HTTP error responses. Common subclasses: NotFoundException, BadRequestException, etc.", code_example: "import { HttpException, HttpStatus, NotFoundException, BadRequestException } from '@nestjs/common';\n\n// 抛出 404\nthrow new NotFoundException('猫不存在');\n\n// 抛出 400\nthrow new BadRequestException('参数错误');\n\n// 自定义状态码\nthrow new HttpException('自定义错误', HttpStatus.FORBIDDEN);", usage_context: ["业务错误处理", "参数验证失败", "资源不存在", "权限不足"], common_mistakes: ["NestJS 内置了常见 HTTP 异常类", "异常会被 ExceptionFilter 捕获", "可以传对象作为响应体"] },
  { keyword: "ValidationPipe", language: "nestjs", category: "NestJS", definition: "内置 Pipe，配合 class-validator 自动验证和转换 DTO 数据。\nBuilt-in Pipe that automatically validates and transforms DTO data with class-validator.", code_example: "import { ValidationPipe } from '@nestjs/common';\n\n// 全局注册\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  app.useGlobalPipes(new ValidationPipe({\n    whitelist: true,        // 剔除未声明的属性\n    forbidNonWhitelisted: true, // 有未知属性则报错\n    transform: true,        // 自动转换类型\n  }));\n  await app.listen(3000);\n}", usage_context: ["全局 DTO 验证", "请求数据清洗", "类型自动转换"], common_mistakes: ["需要安装 class-validator 和 class-transformer", "whitelist 只保留 DTO 中声明的字段", "transform 自动将字符串转为数字等"] },

  // ── NestJS 数据库 ──
  { keyword: "@Entity", language: "nestjs", category: "NestJS 数据库", definition: "TypeORM 装饰器，将类标记为数据库表实体。\nTypeORM decorator; marks a class as a database table entity.", code_example: "import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';\n\n@Entity('cats')\nexport class Cat {\n  @PrimaryGeneratedColumn()\n  id: number;\n\n  @Column()\n  name: string;\n\n  @Column({ default: 0 })\n  age: number;\n}", usage_context: ["数据库表定义", "ORM 映射", "数据模型"], common_mistakes: ["表名可以自定义（默认类名小写）", "需要在模块中导入 TypeOrmModule.forFeature()"] },
  { keyword: "@Column", language: "nestjs", category: "NestJS 数据库", definition: "TypeORM 装饰器，将属性映射为数据库列。\nTypeORM decorator; maps a property to a database column.", code_example: "@Entity()\nexport class User {\n  @PrimaryGeneratedColumn()\n  id: number;\n\n  @Column({ length: 50 })\n  name: string;\n\n  @Column({ unique: true })\n  email: string;\n\n  @Column({ nullable: true })\n  avatar: string;\n\n  @CreateDateColumn()\n  createdAt: Date;\n}", usage_context: ["数据库列定义", "字段约束（长度、唯一、可空）", "自动时间戳"], common_mistakes: ["默认类型根据 TS 类型推断", "可以用 type 显式指定数据库类型", "nullable 控制是否允许 NULL"] },

  // ── NestJS 高级 ──
  { keyword: "@Global", language: "nestjs", category: "NestJS", definition: "模块级装饰器，将模块标记为全局模块，其 exports 可在任何模块中注入。\nModule decorator; marks a module as global, making its exports injectable anywhere.", code_example: "@Global()\n@Module({\n  providers: [ConfigService],\n  exports: [ConfigService],\n})\nexport class ConfigModule {}", usage_context: ["全局配置服务", "全局日志服务", "减少重复导入"], common_mistakes: ["全局模块应谨慎使用（增加耦合）", "通常只用于真正全局的服务", "每个应用只能有一个全局模块（推荐）"] },
  { keyword: "@MessagePattern", language: "nestjs", category: "NestJS 微服务", definition: "微服务装饰器，监听指定消息模式并处理请求-响应式消息。\nMicroservice decorator; listens for a message pattern and handles request-response messages.", code_example: "import { MessagePattern } from '@nestjs/microservices';\n\n@Controller()\nexport class MathController {\n  @MessagePattern({ cmd: 'sum' })\n  sum(data: number[]): number {\n    return data.reduce((a, b) => a + b, 0);\n  }\n}", usage_context: ["微服务间通信", "RPC 调用", "消息队列消费"], common_mistakes: ["需要配置微服务传输层（TCP/Redis/NATS 等）", "请求-响应模式（有返回值）"] },
  { keyword: "@EventPattern", language: "nestjs", category: "NestJS 微服务", definition: "微服务装饰器，监听事件模式并处理事件驱动消息（无返回值）。\nMicroservice decorator; listens for event patterns and handles event-driven messages (no return).", code_example: "import { EventPattern } from '@nestjs/microservices';\n\n@Controller()\nexport class NotificationController {\n  @EventPattern('user_created')\n  handleUserCreated(data: { email: string }) {\n    console.log(`发送欢迎邮件到 ${data.email}`);\n  }\n}", usage_context: ["事件驱动架构", "异步通知", "日志/审计"], common_mistakes: ["无返回值（fire-and-forget）", "与 @MessagePattern 的区别在于是否需要响应"] },
  { keyword: "@WebSocketGateway", language: "nestjs", category: "NestJS WebSocket", definition: "装饰器，将类标记为 WebSocket 网关，处理实时双向通信。\nDecorator that marks a class as a WebSocket gateway for real-time bidirectional communication.", code_example: "import { WebSocketGateway, WebSocketServer, SubscribeMessage, MessageBody } from '@nestjs/websockets';\nimport { Server } from 'socket.io';\n\n@WebSocketGateway({ cors: true })\nexport class ChatGateway {\n  @WebSocketServer()\n  server: Server;\n\n  @SubscribeMessage('message')\n  handleMessage(@MessageBody() data: string): void {\n    this.server.emit('message', data);\n  }\n}", usage_context: ["实时聊天", "通知推送", "实时数据同步", "游戏服务器"], common_mistakes: ["需要安装 @nestjs/websockets 和 socket.io", "用 @SubscribeMessage 监听客户端消息", "用 @WebSocketServer 注入 Server 实例"] },
  { keyword: "TestingModule", language: "nestjs", category: "NestJS 测试", definition: "NestJS 测试工具，创建隔离的测试模块，用于单元测试和集成测试。\nNestJS testing utility; creates isolated test modules for unit and integration tests.", code_example: "import { Test, TestingModule } from '@nestjs/testing';\nimport { CatsService } from './cats.service';\n\ndescribe('CatsService', () => {\n  let service: CatsService;\n\n  beforeEach(async () => {\n    const module: TestingModule = await Test.createTestingModule({\n      providers: [CatsService],\n    }).compile();\n    service = module.get<CatsService>(CatsService);\n  });\n\n  it('should return cats', () => {\n    expect(service.findAll()).toEqual([]);\n  });\n});", usage_context: ["单元测试", "集成测试", "Mock 依赖注入"], common_mistakes: ["用 .compile() 完成模块编译", "用 .overrideProvider() 替换依赖", "用 module.get() 获取实例"] },
]

async function main() {
  const SQL = await initSqlJs({
    locateFile: file => path.join(ROOT, 'public', file)
  })

  const db = new SQL.Database()
  db.run(`
    CREATE TABLE seed_keywords (
      keyword TEXT,
      language TEXT,
      category TEXT,
      definition TEXT,
      code_example TEXT,
      usage_context TEXT,
      common_mistakes TEXT,
      PRIMARY KEY (language, keyword)
    )
  `)

  const stmt = db.prepare('INSERT INTO seed_keywords (keyword, language, category, definition, code_example, usage_context, common_mistakes) VALUES (?, ?, ?, ?, ?, ?, ?)')
  for (const kw of KEYWORDS) {
    stmt.run([kw.keyword, kw.language, kw.category, kw.definition, kw.code_example, JSON.stringify(kw.usage_context), JSON.stringify(kw.common_mistakes)])
  }
  stmt.free()

  const data = db.export()
  const outPath = path.join(ROOT, 'public', 'seed.db')
  fs.writeFileSync(outPath, Buffer.from(data))
  console.log(`Generated ${outPath} — ${KEYWORDS.length} keywords, ${data.length} bytes`)
  db.close()
}

main().catch(e => { console.error(e); process.exit(1) })
